import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tech_world/events/dispatch.dart';
import 'package:tech_world/events/types.dart';
import 'package:tech_world/progress/progress_service.dart';
import 'package:tech_world/prompt/prompt_challenge.dart';
import 'package:tech_world/spellbook/cast_effects.dart';
import 'package:tech_world/spellbook/spellbook_service.dart';
import 'package:tech_world/spellbook/word_of_power.dart';

import 'sinks/architecture_capture.dart';

/// Architecture Contract: cast_effects.dart
///
/// Codifies the public interface of lib/spellbook/cast_effects.dart.
/// Two exported functions: castSuccessEvents (pure) and applyCastSuccessEffects (effectful).
///
/// Generated by /tw-architecture-sweep
void main() {
  late ArchitectureCaptureSink sink;

  setUp(() {
    sink = ArchitectureCaptureSink('cast_effects');
    registerSink(sink.sink);
  });

  tearDown(clearSinks);

  // ── Public interface ─────────────────────────────────────────────────────

  group('castSuccessEvents (pure function)', () {
    test('returns List<AppEvent>', () {
      final events = castSuccessEvents(PromptChallengeId.evocationFizzbuzz);
      expect(events, isA<List<AppEvent>>());
    });

    test('produces at least one event per challenge', () {
      for (final id in PromptChallengeId.values) {
        final events = castSuccessEvents(id);
        expect(events, isNotEmpty,
            reason: '${id.name} must produce at least one event');
      }
    });

    test('always produces ChallengeCompleted as last event', () {
      for (final id in PromptChallengeId.values) {
        final events = castSuccessEvents(id);
        expect(events.last, isA<ChallengeCompleted>(),
            reason: '${id.name} must end with ChallengeCompleted');
      }
    });

    test('produces WordLearned as first event when challenge has a word', () {
      final events = castSuccessEvents(PromptChallengeId.evocationFizzbuzz);
      expect(events.first, isA<WordLearned>());
      final wordEvent = events.first as WordLearned;
      expect(wordEvent.wordId, WordId.ignis);
      expect(wordEvent.challengeId, PromptChallengeId.evocationFizzbuzz);
    });

    test('does NOT dispatch events (pure — no side effects)', () {
      castSuccessEvents(PromptChallengeId.evocationFizzbuzz);
      expect(sink.captured, isEmpty);
    });
  });

  // ── applyCastSuccessEffects return shape ──────────────────────────────────

  group('applyCastSuccessEffects return shape', () {
    late SpellbookService spellbook;
    late ProgressService progress;

    setUp(() async {
      final firestore = FakeFirebaseFirestore();
      spellbook = SpellbookService(uid: 'u', collection: firestore.collection('users'));
      progress = ProgressService(uid: 'u', collection: firestore.collection('users'));
      await spellbook.loadSpellbook();
      await progress.loadProgress();
    });

    tearDown(() {
      spellbook.dispose();
      progress.dispose();
    });

    test('returns Future<List<AppEvent>>', () {
      final result = applyCastSuccessEffects(
        challengeId: PromptChallengeId.evocationFizzbuzz,
        spellbook: spellbook,
        progress: progress,
      );
      expect(result, isA<Future<List<AppEvent>>>());
    });

    test('returned events match what castSuccessEvents produces', () async {
      final returned = await applyCastSuccessEffects(
        challengeId: PromptChallengeId.evocationFizzbuzz,
        spellbook: spellbook,
        progress: progress,
      );
      final pure = castSuccessEvents(PromptChallengeId.evocationFizzbuzz);
      expect(returned.length, pure.length);
      for (var i = 0; i < returned.length; i++) {
        expect(returned[i].runtimeType, pure[i].runtimeType);
      }
    });

    test('dispatches the returned events (WordLearned then ChallengeCompleted)', () async {
      await applyCastSuccessEffects(
        challengeId: PromptChallengeId.evocationFizzbuzz,
        spellbook: spellbook,
        progress: progress,
      );
      final types = sink.captured.map((e) => e.runtimeType).toList();
      expect(types, [WordLearned, ChallengeCompleted]);
    });

    test('handles null spellbook gracefully (logs warning, no throw)', () async {
      await expectLater(
        applyCastSuccessEffects(
          challengeId: PromptChallengeId.evocationFizzbuzz,
          spellbook: null,
          progress: progress,
        ),
        completes,
      );
    });

    test('handles null progress gracefully (logs warning, no throw)', () async {
      await expectLater(
        applyCastSuccessEffects(
          challengeId: PromptChallengeId.evocationFizzbuzz,
          spellbook: spellbook,
          progress: null,
        ),
        completes,
      );
    });
  });

  // ── performCast return shape (WithEvents<DoorCastResult>) ─────────────────

  group('performCast returns (DoorCastResult, List<AppEvent>)', () {
    late SpellbookService spellbook;
    late ProgressService progress;

    setUp(() async {
      final firestore = FakeFirebaseFirestore();
      spellbook = SpellbookService(uid: 'u', collection: firestore.collection('users'));
      progress = ProgressService(uid: 'u', collection: firestore.collection('users'));
      await spellbook.loadSpellbook();
      await progress.loadProgress();
    });

    tearDown(() {
      spellbook.dispose();
      progress.dispose();
    });

    test('returns a record (result, events)', () async {
      final tuple = await performCast(
        transcript: 'ignis',
        doorRequiredChallenges: [PromptChallengeId.evocationFizzbuzz],
        spellbook: spellbook,
        progress: progress,
      );
      expect(tuple.$1, isNotNull); // DoorCastResult
      expect(tuple.$2, isA<List<AppEvent>>());
    });

    test('no match returns empty event list and no dispatch', () async {
      final (_, events) = await performCast(
        transcript: 'abracadabra',
        doorRequiredChallenges: [PromptChallengeId.evocationFizzbuzz],
        spellbook: spellbook,
        progress: progress,
      );
      expect(events, isEmpty);
      expect(sink.captured, isEmpty);
    });
  });
}
