import 'package:flutter_test/flutter_test.dart';
import 'package:tech_world/events/dispatch.dart';
import 'package:tech_world/events/types.dart';

import 'sinks/architecture_capture.dart';

/// Architecture Contract: events/dispatch.dart
///
/// Codifies the public interface of lib/events/dispatch.dart.
/// Fan-out, snapshot iteration, sync+async sinks.
///
/// Generated by /tw-architecture-sweep
void main() {
  tearDown(clearSinks);

  // ── Public exports exist ─────────────────────────────────────────────────

  group('public interface', () {
    test('registerSink accepts a Sink function', () {
      registerSink((_) {});
    });

    test('registerAsyncSink accepts an AsyncSink function', () {
      registerAsyncSink((_) async {});
    });

    test('sinksRegistered is false before registration', () {
      expect(sinksRegistered, isFalse);
    });

    test('sinksRegistered is true after registerSink', () {
      registerSink((_) {});
      expect(sinksRegistered, isTrue);
    });

    test('dispatch accepts an empty list without error', () {
      dispatch([]);
    });

    test('clearSinks removes all registered sinks', () {
      registerSink((_) {});
      clearSinks();
      expect(sinksRegistered, isFalse);
    });
  });

  // ── Fan-out behaviour ────────────────────────────────────────────────────

  group('fan-out', () {
    test('single sink receives all dispatched events', () {
      final sink = ArchitectureCaptureSink('fan-out');
      registerSink(sink.sink);

      dispatch([
        UserSignedIn(userId: 'u1', displayName: 'Alice'),
        UserSignedOut(),
      ]);

      expect(sink.captured, hasLength(2));
    });

    test('two sinks both receive every event', () {
      final a = ArchitectureCaptureSink('a');
      final b = ArchitectureCaptureSink('b');
      registerSink(a.sink);
      registerSink(b.sink);

      dispatch([UserSignedOut()]);

      expect(a.captured, hasLength(1));
      expect(b.captured, hasLength(1));
    });

    test('dispatch with no sinks does not throw', () {
      expect(() => dispatch([UserSignedOut()]), returnsNormally);
    });
  });

  // ── Snapshot safety ──────────────────────────────────────────────────────

  group('snapshot safety', () {
    test('sink registered during dispatch does not receive current batch', () {
      final late = ArchitectureCaptureSink('late');
      registerSink((_) {
        // Register a second sink mid-dispatch.
        registerSink(late.sink);
      });

      dispatch([UserSignedOut()]);

      // The second sink was added after the snapshot — it should NOT have
      // received the event that triggered the registration.
      expect(late.captured, isEmpty);
    });
  });

  // ── Async sink ───────────────────────────────────────────────────────────

  group('async sink', () {
    test('async sink is invoked for dispatched events', () async {
      final received = <AppEvent>[];
      registerAsyncSink((event) async => received.add(event));

      dispatch([UserSignedOut()]);
      // Drain microtask queue.
      await Future<void>.delayed(Duration.zero);

      expect(received, hasLength(1));
      expect(received.first, isA<UserSignedOut>());
    });
  });
}
