import 'package:flutter_test/flutter_test.dart';
import 'package:tech_world/livekit/livekit_topic.dart';

/// Architecture Contract: LiveKitTopic
///
/// Codifies the public interface of lib/livekit/livekit_topic.dart.
/// Verifies that the closed set of topic wire strings is consistent and
/// that the enum covers the expected topics.
///
/// Generated by /tw-architecture-sweep
void main() {
  // ── Public interface ─────────────────────────────────────────────────────

  group('LiveKitTopic interface', () {
    test('every value has a non-empty wire string', () {
      for (final topic in LiveKitTopic.values) {
        expect(topic.wire, isNotEmpty,
            reason: '${topic.name} must have a wire string');
      }
    });

    test('all wire strings are unique', () {
      final wires = LiveKitTopic.values.map((t) => t.wire).toList();
      final uniqueWires = wires.toSet();
      expect(wires.length, uniqueWires.length,
          reason: 'duplicate wire strings would cause routing collisions');
    });

    test('tryParse returns correct topic for known wire', () {
      for (final topic in LiveKitTopic.values) {
        expect(LiveKitTopic.tryParse(topic.wire), topic);
      }
    });

    test('tryParse returns null for unknown wire', () {
      expect(LiveKitTopic.tryParse('unknown-topic'), isNull);
    });
  });

  // ── Specific wire values preserved (wire contract with bot/server) ───────

  group('wire values', () {
    test('position wire is "position"', () {
      expect(LiveKitTopic.position.wire, 'position');
    });

    test('positionHeartbeat wire is "position-heartbeat"', () {
      expect(LiveKitTopic.positionHeartbeat.wire, 'position-heartbeat');
    });

    test('chat wire is "chat"', () {
      expect(LiveKitTopic.chat.wire, 'chat');
    });

    test('chatResponse wire is "chat-response"', () {
      expect(LiveKitTopic.chatResponse.wire, 'chat-response');
    });

    test('doorUnlock wire is "door-unlock"', () {
      expect(LiveKitTopic.doorUnlock.wire, 'door-unlock');
    });

    test('speechTranscript wire is "speech-transcript"', () {
      expect(LiveKitTopic.speechTranscript.wire, 'speech-transcript');
    });

    test('mapEdit wire is "map-edit"', () {
      expect(LiveKitTopic.mapEdit.wire, 'map-edit');
    });

    test('mapEditSync wire is "map-edit-sync"', () {
      expect(LiveKitTopic.mapEditSync.wire, 'map-edit-sync');
    });

    test('oracleRequest wire is "oracle-request"', () {
      expect(LiveKitTopic.oracleRequest.wire, 'oracle-request');
    });

    test('oracleResponse wire is "oracle-response"', () {
      expect(LiveKitTopic.oracleResponse.wire, 'oracle-response');
    });

    test('ping wire is "ping"', () {
      expect(LiveKitTopic.ping.wire, 'ping');
    });

    test('pong wire is "pong"', () {
      expect(LiveKitTopic.pong.wire, 'pong');
    });

    test('agentHello wire is "agent-hello"', () {
      // kebab-case for consistency with every other topic in the enum;
      // wire contract pairs with bot-side `AGENT_HELLO = 'agent-hello'`.
      expect(LiveKitTopic.agentHello.wire, 'agent-hello');
    });
  });

  // ── Exhaustiveness guard ─────────────────────────────────────────────────

  group('exhaustiveness', () {
    test('enum covers all expected major topic categories', () {
      final wires = LiveKitTopic.values.map((t) => t.wire).toSet();
      // Core topics that must never disappear — update when deliberately removed.
      const required = {
        'position',
        'position-heartbeat',
        'avatar',
        'chat',
        'chat-response',
        'door-unlock',
        'speech-transcript',
        'map-edit',
        'map-info',
        'ping',
        'pong',
      };
      for (final topic in required) {
        expect(wires, contains(topic),
            reason: '"$topic" must remain in LiveKitTopic');
      }
    });
  });
}
