import 'package:flutter_test/flutter_test.dart';
import 'package:tech_world/utils/locator.dart';

/// Architecture Contract: Locator
///
/// Codifies the public interface of lib/utils/locator.dart.
/// The Locator is a shallow service-locator with a flat map and no lifecycle.
/// These tests document what the interface IS, not what it should be.
///
/// Generated by /tw-architecture-sweep
void main() {
  // Clean up after every test so locator state doesn't leak.
  tearDown(() {
    Locator.remove<_ServiceA>();
    Locator.remove<_ServiceB>();
  });

  group('Locator interface', () {
    test('add and locate a type', () {
      final svc = _ServiceA();
      Locator.add<_ServiceA>(svc);
      expect(locate<_ServiceA>(), same(svc));
    });

    test('maybeLocate returns null when not registered', () {
      expect(Locator.maybeLocate<_ServiceA>(), isNull);
    });

    test('maybeLocate returns value after add', () {
      final svc = _ServiceA();
      Locator.add<_ServiceA>(svc);
      expect(Locator.maybeLocate<_ServiceA>(), same(svc));
    });

    test('remove clears the registration', () {
      Locator.add<_ServiceA>(_ServiceA());
      Locator.remove<_ServiceA>();
      expect(Locator.maybeLocate<_ServiceA>(), isNull);
    });

    test('two distinct types are independently located', () {
      final a = _ServiceA();
      final b = _ServiceB();
      Locator.add<_ServiceA>(a);
      Locator.add<_ServiceB>(b);
      expect(locate<_ServiceA>(), same(a));
      expect(locate<_ServiceB>(), same(b));
    });

    test('overwrite replaces previous registration', () {
      final first = _ServiceA();
      final second = _ServiceA();
      Locator.add<_ServiceA>(first);
      Locator.add<_ServiceA>(second); // default overwrite=true
      expect(locate<_ServiceA>(), same(second));
    });

    test('locate throws a descriptive error for unregistered type', () {
      expect(() => locate<_ServiceA>(), throwsA(isA<String>()));
    });

    test('add with overwrite=false throws when type is already registered', () {
      Locator.add<_ServiceA>(_ServiceA());
      expect(
        () => Locator.add<_ServiceA>(_ServiceA(), overwrite: false),
        throwsA(isA<String>()),
      );
    });
  });
}

class _ServiceA {}
class _ServiceB {}
