import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tech_world/map_editor/map_editor_panel.dart';
import 'package:tech_world/map_editor/map_editor_state.dart';
import 'package:tech_world/map_editor/map_sync_service.dart';

/// Architecture Contract: MapEditorPanel
///
/// Codifies the public interface of lib/map_editor/map_editor_panel.dart.
/// Key architectural invariant: [MapSyncService] is passed as a constructor
/// parameter, NOT resolved via Locator inside the widget.
///
/// Generated by /tw-architecture-sweep
void main() {
  group('MapEditorPanel interface', () {
    test('accepts syncService as an optional constructor parameter', () {
      final state = MapEditorState();
      // Must not throw — syncService is optional (null → offline mode).
      final panel = MapEditorPanel(
        state: state,
        onApply: () async {},
        onCancel: () async {},
        syncService: null,
      );
      expect(panel.syncService, isNull);
      state.dispose();
    });

    test('stores the provided syncService in the field', () async {
      // We can't easily test a real MapSyncService without a LiveKitService,
      // but we can verify the null case and field type.
      final state = MapEditorState();
      final panel = MapEditorPanel(
        state: state,
        onApply: () async {},
        onCancel: () async {},
        syncService: null,
      );
      expect(panel.syncService, isA<MapSyncService?>());
      state.dispose();
    });

    test('syncService field is declared MapSyncService? type', () {
      final state = MapEditorState();
      final panel = MapEditorPanel(
        state: state,
        onApply: () async {},
        onCancel: () async {},
      );
      // Field is accessible — if it's removed this fails to compile.
      expect(panel.syncService, isNull);
      state.dispose();
    });

    test('does not import Locator (dependency made explicit)', () {
      // Indirect: if this file compiled without errors after removing the
      // Locator import from map_editor_panel.dart, the refactor succeeded.
      // We verify by instantiating the panel in offline mode — previously
      // this would call Locator internally.
      final state = MapEditorState();
      expect(
        () => MapEditorPanel(
          state: state,
          onApply: () async {},
          onCancel: () async {},
        ),
        returnsNormally,
      );
      state.dispose();
    });

  });

  testWidgets('builds without syncService (offline mode) — no Locator call', (tester) async {
    final state = MapEditorState();
    final panel = MapEditorPanel(
      state: state,
      onApply: () async {},
      onCancel: () async {},
      syncService: null,
    );

    // Build in a minimal widget tree — should not throw or call Locator.
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(body: panel),
      ),
    );
    // No crash = offline mode works without syncService.
    state.dispose();
  });
}
