import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tech_world/progress/progress_service.dart';

/// Architecture Contract: ProgressService
///
/// Codifies the public interface of lib/progress/progress_service.dart.
/// Hides Firestore read/write behind a clean 4-method interface.
///
/// Generated by /tw-architecture-sweep
void main() {
  late ProgressService service;

  setUp(() async {
    final firestore = FakeFirebaseFirestore();
    service = ProgressService(
      uid: 'test-user',
      collection: firestore.collection('users'),
    );
    await service.loadProgress();
  });

  tearDown(() => service.dispose());

  // ── Public exports ───────────────────────────────────────────────────────

  group('public interface', () {
    test('exposes completedChallenges as Stream<Set<String>>', () {
      expect(service.completedChallenges, isA<Stream<Set<String>>>());
    });

    test('exposes completedCount as int', () {
      expect(service.completedCount, isA<int>());
    });

    test('exposes isChallengeCompleted returning bool', () {
      expect(service.isChallengeCompleted('evocation_fizzbuzz'), isA<bool>());
    });

    test('markChallengeCompleted returns Future', () {
      expect(
        service.markChallengeCompleted('evocation_fizzbuzz'),
        isA<Future>(),
      );
    });
  });

  // ── Module independence ──────────────────────────────────────────────────

  group('independence', () {
    test('can be instantiated with FakeFirebaseFirestore (no live connection)', () {
      final svc = ProgressService(
        uid: 'offline-user',
        collection: FakeFirebaseFirestore().collection('users'),
      );
      svc.dispose();
    });
  });

  // ── Behaviour contracts ──────────────────────────────────────────────────

  group('behaviour', () {
    test('starts with completedCount == 0', () {
      expect(service.completedCount, 0);
    });

    test('isChallengeCompleted returns false for unknown challenge', () {
      expect(service.isChallengeCompleted('unknown_challenge'), isFalse);
    });

    test('markChallengeCompleted makes isChallengeCompleted return true', () async {
      await service.markChallengeCompleted('evocation_fizzbuzz');
      expect(service.isChallengeCompleted('evocation_fizzbuzz'), isTrue);
    });

    test('markChallengeCompleted increments completedCount', () async {
      await service.markChallengeCompleted('evocation_fizzbuzz');
      expect(service.completedCount, 1);
    });

    test('markChallengeCompleted is idempotent (count stays 1)', () async {
      await service.markChallengeCompleted('evocation_fizzbuzz');
      await service.markChallengeCompleted('evocation_fizzbuzz');
      expect(service.completedCount, 1);
    });

    test('markChallengeCompleted emits updated set on stream', () async {
      final emissions = <Set<String>>[];
      service.completedChallenges.listen(emissions.add);

      await service.markChallengeCompleted('conjuration_sort');
      await Future<void>.delayed(Duration.zero);

      expect(emissions, isNotEmpty);
      expect(emissions.last, contains('conjuration_sort'));
    });
  });

  // ── Error boundary ───────────────────────────────────────────────────────

  group('error boundary', () {
    test('loadProgress does not throw when no data exists', () async {
      final svc = ProgressService(
        uid: 'new-user',
        collection: FakeFirebaseFirestore().collection('users'),
      );
      await expectLater(svc.loadProgress(), completes);
      svc.dispose();
    });
  });
}
