import 'dart:math';

import 'package:flutter_test/flutter_test.dart';
import 'package:tech_world/events/dispatch.dart';
import 'package:tech_world/events/types.dart';
import 'package:tech_world/proximity/proximity_service.dart';

import 'sinks/architecture_capture.dart';

/// Architecture Contract: ProximityService
///
/// Codifies the public interface of lib/proximity/proximity_service.dart.
/// If refactoring breaks these, the interface changed — update accordingly.
///
/// Generated by /tw-architecture-sweep
void main() {
  late ArchitectureCaptureSink sink;
  late ProximityService service;

  setUp(() {
    sink = ArchitectureCaptureSink('ProximityService');
    registerSink(sink.sink);
    service = ProximityService(proximityThreshold: 5);
  });

  tearDown(() {
    clearSinks();
    service.dispose();
  });

  // ── Public exports exist with expected types ─────────────────────────────

  group('public interface', () {
    test('exposes nearbyPlayers as unmodifiable Set<String>', () {
      expect(service.nearbyPlayers, isA<Set<String>>());
    });

    test('exposes proximityEvents stream', () {
      expect(service.proximityEvents, isA<Stream<ProximityEvent>>());
    });

    test('exposes checkProximity method', () {
      // Can call without error — interface is stable.
      service.checkProximity(
        localPlayerPosition: const Point(0, 0),
        otherPlayerPositions: {},
      );
    });

    test('calculateOpacity is not a static method on ProximityService (moved to BubbleManager)', () {
      // This test verifies the architectural refactor by checking that calling
      // ProximityService.calculateOpacity does NOT compile. Since we can't
      // assert compilation failure at runtime, we document the intent here:
      // calculateOpacity was removed from ProximityService in the architecture
      // sweep and moved to BubbleManager._opacityForDistance (private).
      // If someone adds it back, `flutter analyze` will catch the deprecation.
      expect(true, isTrue, reason: 'documentation test — see ProximityService source');
    });
  });

  // ── Module independence ──────────────────────────────────────────────────

  group('independence', () {
    test('can be instantiated without any other service', () {
      final svc = ProximityService();
      svc.dispose();
    });

    test('proximityThreshold defaults to 3', () {
      final svc = ProximityService();
      expect(svc.proximityThreshold, 3);
      svc.dispose();
    });

    test('custom threshold is respected', () {
      final svc = ProximityService(proximityThreshold: 3);
      expect(svc.proximityThreshold, 3);
      svc.dispose();
    });
  });

  // ── Event generation ─────────────────────────────────────────────────────

  group('event generation', () {
    test('player entering range produces PlayerEnteredProximity', () {
      service.checkProximity(
        localPlayerPosition: const Point(0, 0),
        otherPlayerPositions: {'p1': const Point(2, 2)},
      );
      expect(sink.ofType<PlayerEnteredProximity>(), hasLength(1));
      expect(sink.ofType<PlayerEnteredProximity>().first.playerId, 'p1');
    });

    test('player leaving range produces PlayerLeftProximity', () {
      service.checkProximity(
        localPlayerPosition: const Point(0, 0),
        otherPlayerPositions: {'p1': const Point(2, 2)},
      );
      sink.clear();

      service.checkProximity(
        localPlayerPosition: const Point(0, 0),
        otherPlayerPositions: {'p1': const Point(20, 20)},
      );
      expect(sink.ofType<PlayerLeftProximity>(), hasLength(1));
    });

    test('no events for out-of-range player', () {
      service.checkProximity(
        localPlayerPosition: const Point(0, 0),
        otherPlayerPositions: {'p1': const Point(20, 20)},
      );
      expect(sink.captured, isEmpty);
    });

    test('does not re-fire enter event when player stays in range', () {
      service.checkProximity(
        localPlayerPosition: const Point(0, 0),
        otherPlayerPositions: {'p1': const Point(2, 2)},
      );
      expect(sink.ofType<PlayerEnteredProximity>(), hasLength(1));
      sink.clear();

      service.checkProximity(
        localPlayerPosition: const Point(0, 0),
        otherPlayerPositions: {'p1': const Point(2, 2)},
      );
      expect(sink.captured, isEmpty);
    });
  });

  // ── Error boundary ───────────────────────────────────────────────────────

  group('error boundary', () {
    test('empty positions map produces no events', () {
      service.checkProximity(
        localPlayerPosition: const Point(10, 10),
        otherPlayerPositions: {},
      );
      expect(sink.captured, isEmpty);
    });

    test('disconnected player fires PlayerLeftProximity', () {
      service.checkProximity(
        localPlayerPosition: const Point(0, 0),
        otherPlayerPositions: {'p1': const Point(2, 2)},
      );
      sink.clear();

      service.checkProximity(
        localPlayerPosition: const Point(0, 0),
        otherPlayerPositions: {},
      );
      expect(sink.ofType<PlayerLeftProximity>(), hasLength(1));
    });
  });
}
