import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tech_world/chat/chat_message_repository.dart';
import 'package:tech_world/chat/chat_service.dart';
import 'package:tech_world/flame/maps/game_map.dart';
import 'dart:math';

import 'package:tech_world/livekit/livekit_service.dart';
import 'package:tech_world/proximity/proximity_service.dart';
import 'package:tech_world/rooms/room_data.dart';
import 'package:tech_world/rooms/room_session.dart';
import 'package:tech_world/utils/locator.dart';

/// Architecture Contract: RoomSession
///
/// Codifies the public interface of lib/rooms/room_session.dart.
/// 4-method factory/connect/enableMedia/leave lifecycle, room-scoped service
/// ownership, and Locator registration contract.
///
/// Generated by /tw-architecture-sweep
void main() {
  const testRoom = RoomData(
    id: 'contract-room',
    name: 'Contract Test Room',
    ownerId: 'user-1',
    ownerDisplayName: 'Test User',
    mapData: GameMap(
      id: 'test_map',
      name: 'Test Map',
      barriers: [Point(1, 2)],
    ),
  );

  RoomSession createSession() => RoomSession.create(
        room: testRoom,
        userId: 'user-1',
        displayName: 'Test User',
        onStateChanged: () {},
        onReconnectWorld: () async {},
        onRoomDeleted: () {},
        chatMessageRepository:
            ChatMessageRepository(firestore: FakeFirebaseFirestore()),
        firestore: FakeFirebaseFirestore(),
      );

  tearDown(() {
    Locator.remove<LiveKitService>();
    Locator.remove<ChatService>();
    Locator.remove<ProximityService>();
  });

  // ── Public interface ─────────────────────────────────────────────────────

  group('public interface', () {
    test('exposes liveKitService', () {
      final s = createSession();
      expect(s.liveKitService, isA<LiveKitService>());
      s.chatService.dispose();
      s.proximityService.dispose();
    });

    test('exposes chatService', () {
      final s = createSession();
      expect(s.chatService, isA<ChatService>());
      s.chatService.dispose();
      s.proximityService.dispose();
    });

    test('exposes proximityService', () {
      final s = createSession();
      expect(s.proximityService, isA<ProximityService>());
      s.chatService.dispose();
      s.proximityService.dispose();
    });

    test('exposes room, userId, displayName', () {
      final s = createSession();
      expect(s.room.id, 'contract-room');
      expect(s.userId, 'user-1');
      expect(s.displayName, 'Test User');
      s.chatService.dispose();
      s.proximityService.dispose();
    });

    test('exposes connectionFailed ValueNotifier<bool>', () {
      final s = createSession();
      expect(s.connectionFailed.value, isFalse);
      s.chatService.dispose();
      s.proximityService.dispose();
    });

    test('exposes connectionMessage ValueNotifier<String?>', () {
      final s = createSession();
      expect(s.connectionMessage.value, isNull);
      s.chatService.dispose();
      s.proximityService.dispose();
    });

    test('failureMessageFor is a static method returning String', () {
      expect(
        RoomSession.failureMessageFor(ConnectionResult.tokenAuthError),
        isA<String>(),
      );
    });
  });

  // ── Locator registration contract ────────────────────────────────────────

  group('Locator registration', () {
    test('create registers LiveKitService, ChatService, ProximityService', () {
      final s = createSession();
      expect(Locator.maybeLocate<LiveKitService>(), same(s.liveKitService));
      expect(Locator.maybeLocate<ChatService>(), same(s.chatService));
      expect(Locator.maybeLocate<ProximityService>(), same(s.proximityService));
      s.chatService.dispose();
      s.proximityService.dispose();
    });

    test('leave removes all three services from Locator', () async {
      final s = createSession();
      await s.leave();
      expect(Locator.maybeLocate<LiveKitService>(), isNull);
      expect(Locator.maybeLocate<ChatService>(), isNull);
      expect(Locator.maybeLocate<ProximityService>(), isNull);
    });
  });

  // ── Module independence ──────────────────────────────────────────────────

  group('independence', () {
    test('can be created without a real LiveKitService token', () {
      expect(createSession, returnsNormally);
    });

    test('oracleService is lazily created (same instance on repeated access)', () {
      final s = createSession();
      expect(s.oracleService, same(s.oracleService));
      s.chatService.dispose();
      s.proximityService.dispose();
    });
  });
}
