import 'package:flutter_test/flutter_test.dart';
import 'package:tech_world/flame/shared/speaker_role.dart';

/// Architecture Contract: SpeakerRole
///
/// Codifies the public interface of lib/flame/shared/speaker_role.dart.
/// This enum replaced the stringly-typed 'dreamfinder'/'user' literals
/// in TechWorld._handleSpeechTranscript.
///
/// Generated by /tw-architecture-sweep
void main() {
  group('SpeakerRole interface', () {
    test('values are dreamfinder and user', () {
      expect(SpeakerRole.values.length, 2);
      expect(SpeakerRole.values, contains(SpeakerRole.dreamfinder));
      expect(SpeakerRole.values, contains(SpeakerRole.user));
    });

    test('wire strings match the old string literals', () {
      expect(SpeakerRole.dreamfinder.wire, 'dreamfinder');
      expect(SpeakerRole.user.wire, 'user');
    });

    test('tryParse returns correct value for known wire', () {
      expect(SpeakerRole.tryParse('dreamfinder'), SpeakerRole.dreamfinder);
      expect(SpeakerRole.tryParse('user'), SpeakerRole.user);
    });

    test('tryParse returns null for unknown wire', () {
      expect(SpeakerRole.tryParse('bot'), isNull);
      expect(SpeakerRole.tryParse(''), isNull);
    });

    test('tryParse returns null for null input', () {
      expect(SpeakerRole.tryParse(null), isNull);
    });

    test('wire strings are non-empty', () {
      for (final role in SpeakerRole.values) {
        expect(role.wire, isNotEmpty);
      }
    });

    test('all wire strings are unique', () {
      final wires = SpeakerRole.values.map((r) => r.wire).toSet();
      expect(wires.length, SpeakerRole.values.length);
    });
  });
}
