import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tech_world/spellbook/spellbook_service.dart';
import 'package:tech_world/spellbook/word_of_power.dart';

/// Architecture Contract: SpellbookService
///
/// Codifies the public interface of lib/spellbook/spellbook_service.dart.
/// Hides Firestore spellbook read/write behind a clean 4-method interface.
///
/// Generated by /tw-architecture-sweep
void main() {
  late SpellbookService service;

  setUp(() async {
    final firestore = FakeFirebaseFirestore();
    service = SpellbookService(
      uid: 'test-user',
      collection: firestore.collection('users'),
    );
    await service.loadSpellbook();
  });

  tearDown(() => service.dispose());

  // ── Public exports ───────────────────────────────────────────────────────

  group('public interface', () {
    test('exposes learnedWords stream', () {
      expect(service.learnedWords, isA<Stream<Set<WordId>>>());
    });

    test('exposes learnedWordIds as Set<WordId>', () {
      expect(service.learnedWordIds, isA<Set<WordId>>());
    });

    test('exposes hasWord method returning bool', () {
      expect(service.hasWord(WordId.ignis), isA<bool>());
    });

    test('exposes count getter returning int', () {
      expect(service.count, isA<int>());
    });

    test('exposes learnWord returning Future', () {
      expect(service.learnWord(WordId.ignis), isA<Future>());
    });
  });

  // ── Module independence ──────────────────────────────────────────────────

  group('independence', () {
    test('can be instantiated with FakeFirebaseFirestore', () {
      final svc = SpellbookService(
        uid: 'offline-user',
        collection: FakeFirebaseFirestore().collection('users'),
      );
      svc.dispose();
    });
  });

  // ── Behaviour contracts ──────────────────────────────────────────────────

  group('behaviour', () {
    test('starts with empty spellbook', () {
      expect(service.count, 0);
      expect(service.learnedWordIds, isEmpty);
    });

    test('hasWord returns false for unlearned word', () {
      expect(service.hasWord(WordId.ignis), isFalse);
    });

    test('learnWord adds word to learnedWordIds', () async {
      await service.learnWord(WordId.ignis);
      expect(service.hasWord(WordId.ignis), isTrue);
      expect(service.count, 1);
    });

    test('learnWord is idempotent', () async {
      await service.learnWord(WordId.ignis);
      await service.learnWord(WordId.ignis);
      expect(service.count, 1);
    });

    test('learnedWords stream emits updated set after learnWord', () async {
      final emissions = <Set<WordId>>[];
      service.learnedWords.listen(emissions.add);

      await service.learnWord(WordId.lumen);
      await Future<void>.delayed(Duration.zero);

      expect(emissions, isNotEmpty);
      expect(emissions.last, contains(WordId.lumen));
    });
  });

  // ── Error boundary ───────────────────────────────────────────────────────

  group('error boundary', () {
    test('loadSpellbook does not throw when no prior data exists', () async {
      final svc = SpellbookService(
        uid: 'new-user',
        collection: FakeFirebaseFirestore().collection('users'),
      );
      await expectLater(svc.loadSpellbook(), completes);
      svc.dispose();
    });
  });
}
