import 'package:tech_world/flame/tiles/tile_ref.dart';
import 'package:tech_world/flame/tiles/tileset.dart';
import 'package:tech_world/map_editor/map_editor_state.dart' show ActiveLayer;

/// Test tileset — a 4x4 grid of colored 32x32 squares for development.
const testTileset = Tileset(
  id: 'test',
  name: 'Test Tileset',
  imagePath: 'tilesets/test_tileset.png',
  tileSize: 32,
  columns: 4,
  rows: 4,
);

// ---------------------------------------------------------------------------
// Modern Office Revamped (LimeZu)
// ---------------------------------------------------------------------------

/// Room Builder Office — walls, floors, furniture foundations (16×14 = 224 tiles).
///
/// Barrier tiles (rows 0–4, indices 0–79): wall corners, edges, T-junctions,
/// wall fills — all structural pieces that block movement.
/// Non-barrier tiles (rows 5+, indices 80–223): floor textures, shadows,
/// brick patterns — passable surfaces.
final roomBuilderOffice = Tileset(
  id: 'room_builder_office',
  name: 'Room Builder Office',
  imagePath: 'tilesets/room_builder_office.png',
  tileSize: 32,
  columns: 16,
  rows: 14,
  barrierTileIndices: _roomBuilderOfficeBarriers,
  layerRowRanges: {
    ActiveLayer.objects: [(0, 5)],
    ActiveLayer.floor: [(5, 14)],
  },
);

/// Wall tiles in room_builder_office: rows 0–4 (indices 0–79).
final Set<int> _roomBuilderOfficeBarriers = {
  for (var i = 0; i < 80; i++) i,
};

/// Modern Office — desks, chairs, computers, decorations (16×53 = 848 tiles).
///
/// Barrier tiles: bottom tiles of vertical runs only (117/848). Multi-cell-tall
/// objects (bookshelves, partitions, plants) have their top tiles excluded —
/// the player walks behind them (y-occlusion handles rendering). Only the
/// bottom/base tile of each vertical run blocks movement. Single-cell objects
/// (chairs, keyboards, monitors) are always kept as barriers.
/// Generated by `tool/refine_modern_office_barriers.py`.
final modernOffice = Tileset(
  id: 'modern_office',
  name: 'Modern Office',
  imagePath: 'tilesets/modern_office.png',
  tileSize: 32,
  columns: 16,
  rows: 53,
  barrierTileIndices: _modernOfficeBarriers,
  availableLayers: {ActiveLayer.objects},
);

// ---------------------------------------------------------------------------
// Modern Exteriors (LimeZu)
// ---------------------------------------------------------------------------

/// Terrains & Fences — grass, dirt, paths, fences (32×74).
///
/// Barrier tiles: fences only (rows 70–73, 28 tiles). Terrain surfaces
/// (grass, dirt, paths, stone) are walkable ground; only fence/railing tiles
/// at the bottom-right of the sheet are tagged as barriers.
final extTerrains = Tileset(
  id: 'ext_terrains',
  name: 'Ext: Terrains & Fences',
  imagePath: 'tilesets/ext_terrains.png',
  tileSize: 32,
  columns: 32,
  rows: 74,
  barrierTileIndices: _extTerrainsBarriers,
  availableLayers: {ActiveLayer.floor},
);

/// Worksite — construction props, barriers, equipment (32×20).
///
/// Barrier tiles: all non-empty tiles (428/640). Construction vehicles,
/// fences, crates, scaffolding, and equipment all block movement.
final extWorksite = Tileset(
  id: 'ext_worksite',
  name: 'Ext: Worksite',
  imagePath: 'tilesets/ext_worksite.png',
  tileSize: 32,
  columns: 32,
  rows: 20,
  barrierTileIndices: _extWorksiteBarriers,
  availableLayers: {ActiveLayer.objects},
);

/// Hotel & Hospital — medical/hotel furniture and walls (32×62).
///
/// Barrier tiles: all non-empty tiles (1219/1984). Almost entirely building
/// facade (hotel + hospital walls, windows, doors, signage).
final extHotelHospital = Tileset(
  id: 'ext_hotel_hospital',
  name: 'Ext: Hotel & Hospital',
  imagePath: 'tilesets/ext_hotel_hospital.png',
  tileSize: 32,
  columns: 32,
  rows: 62,
  barrierTileIndices: _extHotelHospitalBarriers,
  availableLayers: {ActiveLayer.objects},
);

/// School — classrooms, desks, school props (32×116).
///
/// Barrier tiles: non-empty tiles excluding walkable surfaces (1588/3712).
/// Building facade (rows 0–33) and props/furniture (rows 58–98) are barriers.
/// Basketball courts (rows 34–57) and soccer fields (rows 99–115) are excluded
/// as walkable playing surfaces.
final extSchool = Tileset(
  id: 'ext_school',
  name: 'Ext: School',
  imagePath: 'tilesets/ext_school.png',
  tileSize: 32,
  columns: 32,
  rows: 116,
  barrierTileIndices: _extSchoolBarriers,
  layerRowRanges: {
    ActiveLayer.objects: [(0, 34), (58, 99)],
    ActiveLayer.floor: [(34, 58), (99, 116)],
  },
);

/// Office — exterior office buildings, signage, props (32×95).
///
/// Barrier tiles: all non-empty tiles (1583/3040). Entirely building facade —
/// walls, windows, rooflines, satellite dishes, signage.
final extOffice = Tileset(
  id: 'ext_office',
  name: 'Ext: Office',
  imagePath: 'tilesets/ext_office.png',
  tileSize: 32,
  columns: 32,
  rows: 95,
  barrierTileIndices: _extOfficeBarriers,
  availableLayers: {ActiveLayer.objects},
);

// ---------------------------------------------------------------------------
// Barrier tile indices — generated by tool/generate_barrier_indices.py
// Each set contains tile indices with alpha > 0 (non-transparent pixels),
// with per-tileset exclusions for walkable surfaces (courts, fields, terrain).
// ---------------------------------------------------------------------------

/// Bottom tiles of vertical runs in modern_office (117/848).
/// Multi-cell-tall objects have top N-1 tiles excluded; only the bottom tile
/// (the one on the ground) is tagged as a barrier.
/// Generated by `tool/refine_modern_office_barriers.py`.
final Set<int> _modernOfficeBarriers = {
  33, 34, 35, // row 2
  38, 39, 40, // row 2
  43, 44, 45, // row 2
  63, // row 3
  90, 91, 92, // row 5
  97, 98, 99, // row 6
  103, 104, // row 6
  110, 111, // row 6
  140, 141, // row 8
  155, // row 9
  173, // row 10
  211, 212, 213, // row 13
  221, // row 13
  223, // row 13
  240, 241, 242, // row 15
  249, // row 15
  261, 262, // row 16
  282, // row 17
  284, // row 17
  290, // row 18
  321, // row 20
  340, // row 21
  374, 375, // row 23
  382, 383, // row 23
  395, 396, 397, // row 24
  401, 402, // row 25
  404, 405, // row 25
  448, 449, 450, 451, 452, 453, 454, // row 28
  for (int i = 497; i <= 505; i++) i, // rows 31–31 (9 tiles)
  525, // row 32
  538, 539, 540, // row 33
  560, // row 35
  564, // row 35
  574, 575, // row 35
  578, // row 36
  582, // row 36
  588, // row 36
  608, // row 38
  612, // row 38
  626, // row 39
  629, 630, 631, // row 39
  638, // row 39
  648, // row 40
  650, // row 40
  652, // row 40
  656, // row 41
  670, // row 41
  673, // row 42
  680, 681, 682, 683, // row 42
  702, 703, // row 43
  707, // row 44
  711, // row 44
  721, // row 45
  725, // row 45
  755, // row 47
  759, // row 47
  769, // row 48
  772, 773, 774, // row 48
  803, // row 50
  for (int i = 808; i <= 813; i++) i, // rows 50–50 (6 tiles)
  816, 817, 818, // row 51
};

/// Fence/railing tiles in ext_terrains: rows 70–73 only (28/2368).
/// Terrain surfaces (grass, dirt, paths, stone) are intentionally excluded.
final Set<int> _extTerrainsBarriers = {
  for (int i = 2262; i <= 2271; i++) i, // rows 70–70 (10 tiles)
  2294, // row 71
  for (int i = 2296; i <= 2299; i++) i, // row 71
  2301, 2302, 2303, // row 71
  2326, 2327, 2328, // row 72
  2331, 2332, 2333, // row 72
  2358, // row 73
  2360, // row 73
  2363, // row 73
  2365, // row 73
};

/// Construction objects in ext_worksite: all non-empty tiles (428/640).
final Set<int> _extWorksiteBarriers = {
  for (int i = 7; i <= 10; i++) i, // row 0
  for (int i = 12; i <= 19; i++) i, // row 0
  for (int i = 21; i <= 26; i++) i, // row 0
  for (int i = 28; i <= 34; i++) i, // row 0
  for (int i = 36; i <= 51; i++) i, // rows 1–1 (16 tiles)
  for (int i = 53; i <= 58; i++) i, // row 1
  for (int i = 60; i <= 83; i++) i, // rows 1–2 (24 tiles)
  for (int i = 85; i <= 90; i++) i, // row 2
  for (int i = 92; i <= 115; i++) i, // rows 2–3 (24 tiles)
  for (int i = 117; i <= 147; i++) i, // rows 3–4 (31 tiles)
  for (int i = 149; i <= 159; i++) i, // rows 4–4 (11 tiles)
  for (int i = 171; i <= 179; i++) i, // row 5
  for (int i = 181; i <= 198; i++) i, // rows 5–6 (18 tiles)
  for (int i = 203; i <= 211; i++) i, // row 6
  for (int i = 213; i <= 220; i++) i, // row 6
  222, // row 6
  for (int i = 224; i <= 233; i++) i, // rows 7–7 (10 tiles)
  for (int i = 235; i <= 243; i++) i, // row 7
  for (int i = 245; i <= 251; i++) i, // row 7
  for (int i = 253; i <= 265; i++) i, // rows 7–8 (13 tiles)
  for (int i = 270; i <= 275; i++) i, // row 8
  for (int i = 277; i <= 282; i++) i, // row 8
  for (int i = 285; i <= 294; i++) i, // rows 8–9 (10 tiles)
  for (int i = 302; i <= 307; i++) i, // row 9
  for (int i = 309; i <= 314; i++) i, // row 9
  for (int i = 317; i <= 320; i++) i, // row 9
  322, 323, 324, // row 10
  326, // row 10
  for (int i = 334; i <= 339; i++) i, // row 10
  for (int i = 341; i <= 346; i++) i, // row 10
  for (int i = 349; i <= 358; i++) i, // rows 10–11 (10 tiles)
  360, 361, // row 11
  for (int i = 366; i <= 371; i++) i, // row 11
  for (int i = 373; i <= 378; i++) i, // row 11
  for (int i = 381; i <= 390; i++) i, // rows 11–12 (10 tiles)
  392, 393, // row 12
  for (int i = 405; i <= 410; i++) i, // row 12
  413, 414, // row 12
  for (int i = 416; i <= 425; i++) i, // rows 13–13 (10 tiles)
  for (int i = 437; i <= 443; i++) i, // row 13
  445, 446, // row 13
  for (int i = 448; i <= 457; i++) i, // rows 14–14 (10 tiles)
  for (int i = 469; i <= 475; i++) i, // row 14
  for (int i = 480; i <= 489; i++) i, // rows 15–15 (10 tiles)
  for (int i = 501; i <= 507; i++) i, // row 15
  for (int i = 512; i <= 523; i++) i, // rows 16–16 (12 tiles)
  for (int i = 533; i <= 539; i++) i, // row 16
  for (int i = 544; i <= 555; i++) i, // rows 17–17 (12 tiles)
  for (int i = 565; i <= 571; i++) i, // row 17
  for (int i = 576; i <= 587; i++) i, // rows 18–18 (12 tiles)
};

/// Building facade tiles in ext_hotel_hospital: all non-empty (1219/1984).
final Set<int> _extHotelHospitalBarriers = {
  for (int i = 17; i <= 24; i++) i, // row 0
  35, // row 1
  45, // row 1
  for (int i = 49; i <= 57; i++) i, // row 1
  for (int i = 64; i <= 70; i++) i, // row 2
  for (int i = 74; i <= 89; i++) i, // rows 2–2 (16 tiles)
  for (int i = 96; i <= 121; i++) i, // rows 3–3 (26 tiles)
  147, 148, // row 4
  for (int i = 160; i <= 176; i++) i, // rows 5–5 (17 tiles)
  179, 180, // row 5
  211, 212, // row 6
  for (int i = 224; i <= 240; i++) i, // rows 7–7 (17 tiles)
  242, 243, 244, // row 7
  for (int i = 256; i <= 272; i++) i, // rows 8–8 (17 tiles)
  275, 276, // row 8
  for (int i = 288; i <= 304; i++) i, // rows 9–9 (17 tiles)
  307, 308, // row 9
  for (int i = 320; i <= 336; i++) i, // rows 10–10 (17 tiles)
  339, 340, // row 10
  for (int i = 352; i <= 368; i++) i, // rows 11–11 (17 tiles)
  370, 371, 372, // row 11
  for (int i = 384; i <= 400; i++) i, // rows 12–12 (17 tiles)
  403, 404, // row 12
  for (int i = 416; i <= 432; i++) i, // rows 13–13 (17 tiles)
  435, 436, // row 13
  467, 468, // row 14
  for (int i = 480; i <= 496; i++) i, // rows 15–15 (17 tiles)
  for (int i = 512; i <= 528; i++) i, // rows 16–16 (17 tiles)
  for (int i = 544; i <= 560; i++) i, // rows 17–17 (17 tiles)
  for (int i = 576; i <= 592; i++) i, // rows 18–18 (17 tiles)
  for (int i = 640; i <= 656; i++) i, // rows 20–20 (17 tiles)
  for (int i = 672; i <= 688; i++) i, // rows 21–21 (17 tiles)
  for (int i = 704; i <= 720; i++) i, // rows 22–22 (17 tiles)
  for (int i = 736; i <= 754; i++) i, // rows 23–23 (19 tiles)
  for (int i = 768; i <= 786; i++) i, // rows 24–24 (19 tiles)
  for (int i = 800; i <= 818; i++) i, // rows 25–25 (19 tiles)
  for (int i = 832; i <= 850; i++) i, // rows 26–26 (19 tiles)
  for (int i = 864; i <= 882; i++) i, // rows 27–27 (19 tiles)
  for (int i = 896; i <= 914; i++) i, // rows 28–28 (19 tiles)
  for (int i = 930; i <= 935; i++) i, // row 29
  for (int i = 960; i <= 986; i++) i, // rows 30–30 (27 tiles)
  for (int i = 992; i <= 1178; i++) i, // rows 31–36 (187 tiles)
  for (int i = 1184; i <= 1200; i++) i, // rows 37–37 (17 tiles)
  for (int i = 1216; i <= 1242; i++) i, // rows 38–38 (27 tiles)
  for (int i = 1248; i <= 1274; i++) i, // rows 39–39 (27 tiles)
  for (int i = 1280; i <= 1296; i++) i, // rows 40–40 (17 tiles)
  for (int i = 1312; i <= 1338; i++) i, // rows 41–41 (27 tiles)
  for (int i = 1352; i <= 1370; i++) i, // rows 42–42 (19 tiles)
  for (int i = 1385; i <= 1402; i++) i, // rows 43–43 (18 tiles)
  for (int i = 1408; i <= 1415; i++) i, // row 44
  for (int i = 1425; i <= 1434; i++) i, // rows 44–44 (10 tiles)
  for (int i = 1440; i <= 1466; i++) i, // rows 45–45 (27 tiles)
  for (int i = 1480; i <= 1498; i++) i, // rows 46–46 (19 tiles)
  for (int i = 1504; i <= 1511; i++) i, // row 47
  for (int i = 1513; i <= 1530; i++) i, // rows 47–47 (18 tiles)
  for (int i = 1536; i <= 1544; i++) i, // row 48
  for (int i = 1553; i <= 1562; i++) i, // rows 48–48 (10 tiles)
  for (int i = 1568; i <= 1594; i++) i, // rows 49–49 (27 tiles)
  for (int i = 1600; i <= 1626; i++) i, // rows 50–50 (27 tiles)
  for (int i = 1632; i <= 1649; i++) i, // rows 51–51 (18 tiles)
  for (int i = 1664; i <= 1689; i++) i, // rows 52–52 (26 tiles)
  for (int i = 1698; i <= 1701; i++) i, // row 53
  for (int i = 1703; i <= 1721; i++) i, // rows 53–53 (19 tiles)
  for (int i = 1736; i <= 1753; i++) i, // rows 54–54 (18 tiles)
  1771, 1772, // row 55
  1779, 1780, // row 55
  1787, 1788, // row 55
  1792, 1793, 1794, // row 56
  for (int i = 1797; i <= 1863; i++) i, // rows 56–58 (67 tiles)
  1867, 1868, // row 58
  1875, 1876, // row 58
  1883, 1884, // row 58
  for (int i = 1888; i <= 1919; i++) i, // rows 59–59 (32 tiles)
  for (int i = 1928; i <= 1951; i++) i, // rows 60–60 (24 tiles)
};

/// School building + props in ext_school, excluding courts/fields (1588/3712).
/// Excluded: basketball courts (rows 34–57), soccer fields (rows 99–115).
final Set<int> _extSchoolBarriers = {
  for (int i = 42; i <= 45; i++) i, // row 1
  for (int i = 64; i <= 87; i++) i, // rows 2–2 (24 tiles)
  for (int i = 96; i <= 119; i++) i, // rows 3–3 (24 tiles)
  for (int i = 128; i <= 151; i++) i, // rows 4–4 (24 tiles)
  for (int i = 160; i <= 183; i++) i, // rows 5–5 (24 tiles)
  for (int i = 192; i <= 215; i++) i, // rows 6–6 (24 tiles)
  for (int i = 224; i <= 703; i++) i, // rows 7–21 (480 tiles)
  705, 706, 707, // row 22
  for (int i = 710; i <= 721; i++) i, // rows 22–22 (12 tiles)
  724, 725, 726, // row 22
  728, // row 22
  for (int i = 730; i <= 733; i++) i, // row 22
  for (int i = 742; i <= 758; i++) i, // rows 23–23 (17 tiles)
  760, // row 23
  for (int i = 762; i <= 765; i++) i, // row 23
  for (int i = 774; i <= 790; i++) i, // rows 24–24 (17 tiles)
  792, // row 24
  for (int i = 794; i <= 797; i++) i, // row 24
  801, // row 25
  803, // row 25
  805, 806, // row 25
  808, // row 25
  810, // row 25
  for (int i = 818; i <= 822; i++) i, // row 25
  824, // row 25
  833, // row 26
  835, // row 26
  837, 838, // row 26
  840, // row 26
  842, // row 26
  for (int i = 850; i <= 854; i++) i, // row 26
  856, // row 26
  865, // row 27
  867, // row 27
  869, 870, // row 27
  872, // row 27
  874, // row 27
  for (int i = 882; i <= 886; i++) i, // row 27
  888, // row 27
  897, // row 28
  899, // row 28
  901, 902, // row 28
  904, // row 28
  906, // row 28
  for (int i = 914; i <= 917; i++) i, // row 28
  919, 920, 921, // row 28
  929, // row 29
  931, // row 29
  933, 934, // row 29
  936, // row 29
  938, // row 29
  951, 952, 953, // row 29
  961, // row 30
  963, // row 30
  965, 966, // row 30
  968, // row 30
  970, // row 30
  983, 984, 985, // row 30
  993, // row 31
  995, // row 31
  997, 998, // row 31
  1000, // row 31
  1002, // row 31
  1025, // row 32
  1027, // row 32
  1029, 1030, // row 32
  1032, // row 32
  1034, // row 32
  1057, // row 33
  1059, // row 33
  1061, 1062, // row 33
  1064, // row 33
  1066, // row 33
  // rows 34–57 excluded (basketball courts — walkable)
  1858, 1859, // row 58
  1864, 1865, // row 58
  1890, 1891, // row 59
  1896, 1897, // row 59
  for (int i = 1907; i <= 1910; i++) i, // row 59
  for (int i = 1913; i <= 1916; i++) i, // row 59
  for (int i = 1922; i <= 1929; i++) i, // row 60
  for (int i = 1939; i <= 1942; i++) i, // row 60
  for (int i = 1945; i <= 1949; i++) i, // row 60
  for (int i = 1954; i <= 1961; i++) i, // row 61
  1963, 1964, 1965, // row 61
  for (int i = 1971; i <= 1974; i++) i, // row 61
  for (int i = 1977; i <= 1981; i++) i, // row 61
  1984, // row 62
  for (int i = 1986; i <= 1993; i++) i, // row 62
  for (int i = 1995; i <= 1999; i++) i, // row 62
  for (int i = 2003; i <= 2006; i++) i, // row 62
  2009, // row 62
  2012, 2013, // row 62
  2016, // row 63
  2018, 2019, // row 63
  2024, 2025, // row 63
  for (int i = 2027; i <= 2031; i++) i, // row 63
  for (int i = 2034; i <= 2045; i++) i, // rows 63–63 (12 tiles)
  2048, // row 64
  2050, 2051, // row 64
  2053, 2054, // row 64
  2056, 2057, // row 64
  for (int i = 2059; i <= 2063; i++) i, // row 64
  for (int i = 2066; i <= 2077; i++) i, // rows 64–64 (12 tiles)
  2080, // row 65
  2082, 2083, // row 65
  2085, 2086, // row 65
  2088, 2089, // row 65
  2094, 2095, // row 65
  for (int i = 2098; i <= 2109; i++) i, // rows 65–65 (12 tiles)
  2112, // row 66
  2114, 2115, // row 66
  2117, 2118, // row 66
  2120, 2121, // row 66
  for (int i = 2123; i <= 2127; i++) i, // row 66
  for (int i = 2130; i <= 2141; i++) i, // rows 66–66 (12 tiles)
  2145, // row 67
  2149, 2150, // row 67
  2152, 2153, // row 67
  for (int i = 2155; i <= 2159; i++) i, // row 67
  for (int i = 2162; i <= 2173; i++) i, // rows 67–67 (12 tiles)
  2177, // row 68
  2181, 2182, // row 68
  2184, 2185, // row 68
  for (int i = 2194; i <= 2205; i++) i, // rows 68–68 (12 tiles)
  2209, // row 69
  for (int i = 2216; i <= 2221; i++) i, // row 69
  for (int i = 2226; i <= 2237; i++) i, // rows 69–69 (12 tiles)
  2241, // row 70
  for (int i = 2248; i <= 2253; i++) i, // row 70
  for (int i = 2258; i <= 2269; i++) i, // rows 70–70 (12 tiles)
  2273, // row 71
  for (int i = 2280; i <= 2288; i++) i, // row 71
  for (int i = 2290; i <= 2301; i++) i, // rows 71–71 (12 tiles)
  for (int i = 2308; i <= 2320; i++) i, // rows 72–72 (13 tiles)
  for (int i = 2322; i <= 2333; i++) i, // rows 72–72 (12 tiles)
  for (int i = 2340; i <= 2349; i++) i, // rows 73–73 (10 tiles)
  2351, 2352, // row 73
  for (int i = 2354; i <= 2365; i++) i, // rows 73–73 (12 tiles)
  2369, // row 74
  2371, // row 74
  for (int i = 2374; i <= 2378; i++) i, // row 74
  for (int i = 2380; i <= 2397; i++) i, // rows 74–74 (18 tiles)
  for (int i = 2400; i <= 2410; i++) i, // rows 75–75 (11 tiles)
  for (int i = 2412; i <= 2429; i++) i, // rows 75–75 (18 tiles)
  for (int i = 2432; i <= 2442; i++) i, // rows 76–76 (11 tiles)
  for (int i = 2444; i <= 2461; i++) i, // rows 76–76 (18 tiles)
  2465, // row 77
  for (int i = 2468; i <= 2474; i++) i, // row 77
  for (int i = 2476; i <= 2493; i++) i, // rows 77–77 (18 tiles)
  2496, 2497, 2498, // row 78
  2503, 2504, // row 78
  2509, 2510, 2511, // row 78
  for (int i = 2514; i <= 2525; i++) i, // rows 78–78 (12 tiles)
  2528, 2529, 2530, // row 79
  2541, // row 79
  for (int i = 2546; i <= 2557; i++) i, // rows 79–79 (12 tiles)
  2560, // row 80
  2562, // row 80
  2564, 2565, 2566, // row 80
  2568, // row 80
  2570, 2571, 2572, // row 80
  2574, // row 80
  2576, 2577, // row 80
  for (int i = 2579; i <= 2582; i++) i, // row 80
  for (int i = 2585; i <= 2588; i++) i, // row 80
  2594, // row 81
  2600, // row 81
  2606, // row 81
  for (int i = 2611; i <= 2614; i++) i, // row 81
  for (int i = 2617; i <= 2620; i++) i, // row 81
  2624, 2625, // row 82
  for (int i = 2628; i <= 2631; i++) i, // row 82
  for (int i = 2634; i <= 2637; i++) i, // row 82
  2640, 2641, // row 82
  for (int i = 2643; i <= 2646; i++) i, // row 82
  for (int i = 2649; i <= 2652; i++) i, // row 82
  2683, 2684, // row 83
  2688, // row 84
  2690, // row 84
  2692, 2693, 2694, // row 84
  2696, // row 84
  2698, 2699, 2700, // row 84
  2702, // row 84
  for (int i = 2704; i <= 2716; i++) i, // rows 84–84 (13 tiles)
  2718, 2719, 2720, // row 84
  2722, // row 85
  2724, // row 85
  2726, // row 85
  2728, // row 85
  2730, // row 85
  2732, // row 85
  2734, // row 85
  2736, // row 85
  for (int i = 2738; i <= 2748; i++) i, // rows 85–85 (11 tiles)
  for (int i = 2750; i <= 2754; i++) i, // row 85
  for (int i = 2756; i <= 2760; i++) i, // row 86
  for (int i = 2762; i <= 2766; i++) i, // row 86
  for (int i = 2768; i <= 2775; i++) i, // row 86
  for (int i = 2777; i <= 2780; i++) i, // row 86
  2782, 2783, // row 86
  2786, 2787, // row 87
  2792, 2793, // row 87
  2798, 2799, // row 87
  for (int i = 2802; i <= 2816; i++) i, // rows 87–88 (15 tiles)
  2818, // row 88
  2820, // row 88
  2822, // row 88
  2824, // row 88
  2826, // row 88
  2828, // row 88
  2830, // row 88
  2832, // row 88
  for (int i = 2834; i <= 2848; i++) i, // rows 88–89 (15 tiles)
  2850, // row 89
  2852, 2853, 2854, // row 89
  2856, // row 89
  2858, 2859, 2860, // row 89
  2862, // row 89
  for (int i = 2864; i <= 2868; i++) i, // row 89
  2870, 2871, // row 89
  for (int i = 2875; i <= 2880; i++) i, // row 89
  2882, // row 90
  2886, // row 90
  2888, // row 90
  2892, // row 90
  2894, // row 90
  for (int i = 2898; i <= 2910; i++) i, // rows 90–90 (13 tiles)
  2912, // row 91
  2914, // row 91
  2916, // row 91
  2918, // row 91
  2920, // row 91
  2922, // row 91
  2924, // row 91
  2926, // row 91
  2928, // row 91
  for (int i = 2930; i <= 2942; i++) i, // rows 91–91 (13 tiles)
  2944, // row 92
  2946, // row 92
  2948, // row 92
  2950, // row 92
  2952, // row 92
  2954, // row 92
  2956, // row 92
  2958, // row 92
  2960, // row 92
  for (int i = 2962; i <= 2976; i++) i, // rows 92–93 (15 tiles)
  2978, // row 93
  2980, // row 93
  2982, // row 93
  2984, // row 93
  2986, // row 93
  2988, // row 93
  2990, // row 93
  2992, // row 93
  for (int i = 2994; i <= 3008; i++) i, // rows 93–94 (15 tiles)
  3012, // row 94
  3014, // row 94
  3018, // row 94
  3020, // row 94
  3024, // row 94
  for (int i = 3026; i <= 3035; i++) i, // rows 94–94 (10 tiles)
  3037, 3038, // row 94
  3040, 3041, // row 95
  3045, 3046, // row 95
  3048, 3049, // row 95
  3053, 3054, // row 95
  3058, // row 95
  for (int i = 3060; i <= 3068; i++) i, // row 95
  3070, // row 95
  for (int i = 3072; i <= 3078; i++) i, // row 96
  3080, 3081, // row 96
  3085, 3086, // row 96
  for (int i = 3090; i <= 3096; i++) i, // row 96
  for (int i = 3099; i <= 3102; i++) i, // row 96
  for (int i = 3104; i <= 3110; i++) i, // row 97
  for (int i = 3112; i <= 3118; i++) i, // row 97
  3122, 3123, 3124, // row 97
  3132, 3133, 3134, // row 97
  for (int i = 3136; i <= 3142; i++) i, // row 98
  3146, 3147, 3148, // row 98
  3154, 3155, 3156, // row 98
  3164, 3165, 3166, // row 98
  // rows 99–115 excluded (soccer fields — walkable)
};

/// Building facade tiles in ext_office: all non-empty (1583/3040).
final Set<int> _extOfficeBarriers = {
  32, 33, // row 1
  35, 36, 37, // row 1
  42, 43, // row 1
  45, 46, 47, // row 1
  49, 50, // row 1
  52, 53, // row 1
  55, 56, 57, // row 1
  59, 60, // row 1
  64, 65, // row 2
  67, 68, 69, // row 2
  74, 75, // row 2
  77, 78, 79, // row 2
  81, 82, // row 2
  84, 85, // row 2
  87, 88, 89, // row 2
  91, 92, // row 2
  96, 97, // row 3
  99, 100, 101, // row 3
  106, 107, // row 3
  109, 110, 111, // row 3
  113, 114, // row 3
  116, 117, // row 3
  119, 120, 121, // row 3
  123, 124, // row 3
  128, 129, // row 4
  131, 132, 133, // row 4
  138, 139, // row 4
  141, 142, 143, // row 4
  145, 146, // row 4
  for (int i = 148; i <= 156; i++) i, // row 4
  160, 161, // row 5
  163, 164, 165, // row 5
  170, 171, // row 5
  173, 174, 175, // row 5
  177, 178, // row 5
  180, 181, // row 5
  183, 184, 185, // row 5
  187, 188, // row 5
  192, 193, // row 6
  195, 196, 197, // row 6
  199, 200, // row 6
  202, 203, // row 6
  205, 206, 207, // row 6
  209, 210, // row 6
  212, 213, // row 6
  215, 216, 217, // row 6
  219, 220, // row 6
  224, 225, // row 7
  227, 228, 229, // row 7
  231, 232, // row 7
  256, 257, // row 8
  259, 260, 261, // row 8
  263, 264, // row 8
  266, 267, // row 8
  269, 270, 271, // row 8
  273, 274, // row 8
  276, 277, // row 8
  279, 280, 281, // row 8
  283, 284, // row 8
  288, 289, // row 9
  291, 292, 293, // row 9
  295, 296, // row 9
  298, 299, // row 9
  301, 302, 303, // row 9
  305, 306, // row 9
  308, 309, // row 9
  311, 312, 313, // row 9
  315, 316, // row 9
  320, 321, // row 10
  323, 324, 325, // row 10
  327, 328, // row 10
  330, 331, // row 10
  333, 334, 335, // row 10
  337, 338, // row 10
  340, 341, // row 10
  343, 344, 345, // row 10
  347, 348, // row 10
  384, 385, // row 12
  387, 388, 389, // row 12
  391, 392, // row 12
  394, 395, // row 12
  397, 398, 399, // row 12
  401, 402, // row 12
  404, 405, // row 12
  407, 408, 409, // row 12
  411, 412, // row 12
  416, 417, // row 13
  419, 420, 421, // row 13
  423, 424, // row 13
  426, 427, // row 13
  429, 430, 431, // row 13
  433, 434, // row 13
  436, 437, // row 13
  439, 440, 441, // row 13
  443, 444, // row 13
  448, 449, // row 14
  451, 452, 453, // row 14
  455, 456, // row 14
  458, 459, // row 14
  461, 462, 463, // row 14
  465, 466, // row 14
  468, 469, // row 14
  471, 472, 473, // row 14
  475, 476, // row 14
  for (int i = 480; i <= 488; i++) i, // row 15
  490, 491, // row 15
  493, 494, 495, // row 15
  497, 498, // row 15
  500, 501, // row 15
  503, 504, 505, // row 15
  507, 508, // row 15
  512, 513, // row 16
  515, 516, 517, // row 16
  519, 520, // row 16
  522, 523, // row 16
  525, 526, 527, // row 16
  529, 530, // row 16
  532, 533, // row 16
  535, 536, 537, // row 16
  539, 540, // row 16
  544, 545, // row 17
  547, 548, 549, // row 17
  551, 552, // row 17
  554, 555, // row 17
  557, 558, 559, // row 17
  561, 562, // row 17
  564, 565, // row 17
  567, 568, 569, // row 17
  571, 572, // row 17
  596, 597, // row 18
  599, 600, 601, // row 18
  603, 604, // row 18
  608, 609, // row 19
  611, 612, 613, // row 19
  615, 616, // row 19
  618, 619, // row 19
  621, 622, 623, // row 19
  625, 626, // row 19
  628, 629, // row 19
  631, 632, 633, // row 19
  635, 636, // row 19
  640, 641, // row 20
  643, 644, 645, // row 20
  647, 648, // row 20
  650, 651, // row 20
  653, 654, 655, // row 20
  657, 658, // row 20
  660, 661, // row 20
  663, 664, 665, // row 20
  667, 668, // row 20
  672, 673, // row 21
  675, 676, 677, // row 21
  679, 680, // row 21
  682, 683, // row 21
  685, 686, 687, // row 21
  689, 690, // row 21
  692, 693, // row 21
  695, 696, 697, // row 21
  699, 700, // row 21
  724, 725, // row 22
  727, 728, 729, // row 22
  731, 732, // row 22
  756, 757, // row 23
  759, 760, 761, // row 23
  763, 764, // row 23
  768, 769, // row 24
  771, 772, // row 24
  774, 775, // row 24
  777, 778, // row 24
  780, 781, // row 24
  783, 784, // row 24
  789, 790, 791, // row 24
  793, 794, 795, // row 24
  800, 801, // row 25
  803, 804, // row 25
  806, 807, // row 25
  809, 810, // row 25
  812, 813, // row 25
  815, 816, // row 25
  821, 822, 823, // row 25
  825, 826, 827, // row 25
  832, // row 26
  836, // row 26
  838, // row 26
  842, // row 26
  844, // row 26
  848, // row 26
  853, 854, 855, // row 26
  857, 858, 859, // row 26
  for (int i = 882; i <= 887; i++) i, // row 27
  889, 890, 891, // row 27
  896, // row 28
  900, // row 28
  902, // row 28
  906, // row 28
  908, // row 28
  912, // row 28
  914, 915, 916, // row 28
  928, // row 29
  932, // row 29
  934, // row 29
  938, // row 29
  940, // row 29
  944, // row 29
  for (int i = 946; i <= 955; i++) i, // rows 29–29 (10 tiles)
  for (int i = 978; i <= 987; i++) i, // rows 30–30 (10 tiles)
  992, // row 31
  996, // row 31
  998, // row 31
  1002, // row 31
  1004, // row 31
  1008, // row 31
  for (int i = 1010; i <= 1017; i++) i, // row 31
  1024, // row 32
  1028, // row 32
  1030, // row 32
  1034, // row 32
  1036, // row 32
  1040, // row 32
  for (int i = 1042; i <= 1049; i++) i, // row 32
  1051, 1052, // row 32
  1056, // row 33
  1060, // row 33
  1062, // row 33
  1066, // row 33
  1068, // row 33
  1072, // row 33
  for (int i = 1076; i <= 1084; i++) i, // row 33
  1088, // row 34
  1092, // row 34
  1094, // row 34
  1098, // row 34
  1100, // row 34
  1104, // row 34
  for (int i = 1108; i <= 1116; i++) i, // row 34
  1152, 1153, 1154, // row 36
  1156, 1157, 1158, // row 36
  1161, 1162, 1163, // row 36
  1165, 1166, 1167, // row 36
  1170, 1171, 1172, // row 36
  1174, 1175, 1176, // row 36
  1184, 1185, 1186, // row 37
  1188, 1189, 1190, // row 37
  1193, 1194, 1195, // row 37
  1197, 1198, 1199, // row 37
  1202, 1203, 1204, // row 37
  1206, 1207, 1208, // row 37
  1216, 1217, 1218, // row 38
  1220, 1221, 1222, // row 38
  1225, 1226, 1227, // row 38
  1229, 1230, 1231, // row 38
  1234, 1235, 1236, // row 38
  1238, 1239, 1240, // row 38
  1280, // row 40
  1282, 1283, // row 40
  1285, // row 40
  1298, // row 40
  1300, 1301, // row 40
  1303, // row 40
  1312, // row 41
  1314, 1315, // row 41
  1317, 1318, 1319, // row 41
  1321, // row 41
  1323, 1324, // row 41
  1326, 1327, 1328, // row 41
  1330, // row 41
  1332, 1333, // row 41
  1335, 1336, 1337, // row 41
  1344, // row 42
  1346, 1347, // row 42
  1349, 1350, 1351, // row 42
  1353, // row 42
  1355, 1356, // row 42
  1358, 1359, 1360, // row 42
  1362, // row 42
  1364, 1365, // row 42
  1367, 1368, 1369, // row 42
  1376, // row 43
  1378, 1379, // row 43
  1381, 1382, 1383, // row 43
  1385, // row 43
  1387, 1388, // row 43
  1390, 1391, 1392, // row 43
  1394, // row 43
  1396, 1397, // row 43
  1399, 1400, 1401, // row 43
  1408, 1409, 1410, // row 44
  1412, 1413, // row 44
  1415, // row 44
  1417, 1418, 1419, // row 44
  1421, 1422, // row 44
  1424, // row 44
  1426, 1427, 1428, // row 44
  1430, 1431, // row 44
  1433, // row 44
  1440, 1441, 1442, // row 45
  1444, 1445, // row 45
  1447, // row 45
  1449, 1450, 1451, // row 45
  1453, 1454, // row 45
  1456, // row 45
  1458, 1459, 1460, // row 45
  1462, 1463, // row 45
  1465, // row 45
  1472, 1473, 1474, // row 46
  1476, 1477, // row 46
  1479, // row 46
  1481, 1482, 1483, // row 46
  1485, 1486, // row 46
  1488, // row 46
  1490, 1491, 1492, // row 46
  1494, 1495, // row 46
  1497, // row 46
  1536, // row 48
  1538, 1539, // row 48
  1541, // row 48
  1545, // row 48
  1547, 1548, // row 48
  1550, // row 48
  1554, // row 48
  1556, 1557, // row 48
  1559, // row 48
  1568, // row 49
  1570, 1571, // row 49
  1573, 1574, 1575, // row 49
  1577, // row 49
  1579, 1580, // row 49
  1582, 1583, 1584, // row 49
  1586, // row 49
  1588, 1589, // row 49
  1591, 1592, 1593, // row 49
  1600, // row 50
  1602, 1603, // row 50
  1605, 1606, 1607, // row 50
  1609, // row 50
  1611, 1612, // row 50
  1614, 1615, 1616, // row 50
  1618, // row 50
  1620, 1621, // row 50
  1623, 1624, 1625, // row 50
  1632, // row 51
  1634, 1635, // row 51
  1637, 1638, 1639, // row 51
  1641, // row 51
  1643, 1644, // row 51
  1646, 1647, 1648, // row 51
  1650, // row 51
  1652, 1653, // row 51
  1655, 1656, 1657, // row 51
  1664, 1665, 1666, // row 52
  1668, 1669, // row 52
  1671, // row 52
  1673, 1674, 1675, // row 52
  1677, 1678, // row 52
  1680, // row 52
  1682, 1683, 1684, // row 52
  1686, 1687, // row 52
  1689, // row 52
  1696, 1697, 1698, // row 53
  1700, 1701, // row 53
  1703, // row 53
  1705, 1706, 1707, // row 53
  1709, 1710, // row 53
  1712, // row 53
  1714, 1715, 1716, // row 53
  1718, 1719, // row 53
  1721, // row 53
  1728, 1729, 1730, // row 54
  1732, 1733, // row 54
  1735, // row 54
  1737, 1738, 1739, // row 54
  1741, 1742, // row 54
  1744, // row 54
  1746, 1747, 1748, // row 54
  1750, 1751, // row 54
  1753, // row 54
  1792, 1793, 1794, // row 56
  1796, 1797, 1798, // row 56
  for (int i = 1802; i <= 1820; i++) i, // rows 56–56 (19 tiles)
  1824, 1825, 1826, // row 57
  1828, 1829, 1830, // row 57
  for (int i = 1834; i <= 1852; i++) i, // rows 57–57 (19 tiles)
  1856, 1857, 1858, // row 58
  1860, 1861, 1862, // row 58
  for (int i = 1866; i <= 1884; i++) i, // rows 58–58 (19 tiles)
  for (int i = 1898; i <= 1916; i++) i, // rows 59–59 (19 tiles)
  for (int i = 1930; i <= 1948; i++) i, // rows 60–60 (19 tiles)
  1952, // row 61
  1954, 1955, // row 61
  1957, 1958, 1959, // row 61
  for (int i = 1962; i <= 1980; i++) i, // rows 61–61 (19 tiles)
  1984, // row 62
  1986, 1987, // row 62
  1989, 1990, 1991, // row 62
  for (int i = 1994; i <= 2012; i++) i, // rows 62–62 (19 tiles)
  2016, // row 63
  2018, 2019, // row 63
  2021, 2022, 2023, // row 63
  for (int i = 2026; i <= 2044; i++) i, // rows 63–63 (19 tiles)
  2048, 2049, 2050, // row 64
  2052, 2053, // row 64
  2055, // row 64
  for (int i = 2058; i <= 2076; i++) i, // rows 64–64 (19 tiles)
  2080, 2081, 2082, // row 65
  2084, 2085, // row 65
  2087, // row 65
  for (int i = 2090; i <= 2108; i++) i, // rows 65–65 (19 tiles)
  2112, 2113, 2114, // row 66
  2116, 2117, // row 66
  2119, // row 66
  for (int i = 2122; i <= 2140; i++) i, // rows 66–66 (19 tiles)
  for (int i = 2154; i <= 2172; i++) i, // rows 67–67 (19 tiles)
  2176, // row 68
  2178, 2179, // row 68
  2181, // row 68
  for (int i = 2186; i <= 2204; i++) i, // rows 68–68 (19 tiles)
  2208, // row 69
  2210, 2211, // row 69
  2213, 2214, 2215, // row 69
  for (int i = 2218; i <= 2236; i++) i, // rows 69–69 (19 tiles)
  2240, // row 70
  2242, 2243, // row 70
  2245, 2246, 2247, // row 70
  for (int i = 2250; i <= 2268; i++) i, // rows 70–70 (19 tiles)
  2272, // row 71
  2274, 2275, // row 71
  2277, 2278, 2279, // row 71
  for (int i = 2282; i <= 2300; i++) i, // rows 71–71 (19 tiles)
  2304, 2305, 2306, // row 72
  2308, 2309, // row 72
  2311, // row 72
  for (int i = 2314; i <= 2332; i++) i, // rows 72–72 (19 tiles)
  2336, 2337, 2338, // row 73
  2340, 2341, // row 73
  2343, // row 73
  for (int i = 2346; i <= 2359; i++) i, // rows 73–73 (14 tiles)
  2368, 2369, 2370, // row 74
  2372, 2373, // row 74
  2375, // row 74
  2413, 2414, // row 75
  2416, 2417, // row 75
  for (int i = 2432; i <= 2442; i++) i, // rows 76–76 (11 tiles)
  for (int i = 2444; i <= 2449; i++) i, // row 76
  2452, 2453, 2454, // row 76
  for (int i = 2464; i <= 2474; i++) i, // rows 77–77 (11 tiles)
  for (int i = 2476; i <= 2486; i++) i, // rows 77–77 (11 tiles)
  for (int i = 2496; i <= 2506; i++) i, // rows 78–78 (11 tiles)
  for (int i = 2508; i <= 2518; i++) i, // rows 78–78 (11 tiles)
  for (int i = 2528; i <= 2538; i++) i, // rows 79–79 (11 tiles)
  for (int i = 2540; i <= 2545; i++) i, // row 79
  2548, 2549, 2550, // row 79
  for (int i = 2560; i <= 2570; i++) i, // rows 80–80 (11 tiles)
  2572, 2573, 2574, // row 80
  2576, 2577, // row 80
  2580, 2581, 2582, // row 80
  for (int i = 2592; i <= 2602; i++) i, // rows 81–81 (11 tiles)
  for (int i = 2604; i <= 2609; i++) i, // row 81
  2611, 2612, 2613, // row 81
  for (int i = 2624; i <= 2634; i++) i, // rows 82–82 (11 tiles)
  for (int i = 2636; i <= 2646; i++) i, // rows 82–82 (11 tiles)
  for (int i = 2656; i <= 2666; i++) i, // rows 83–83 (11 tiles)
  for (int i = 2688; i <= 2703; i++) i, // rows 84–84 (16 tiles)
  for (int i = 2720; i <= 2735; i++) i, // rows 85–85 (16 tiles)
  for (int i = 2752; i <= 2767; i++) i, // rows 86–86 (16 tiles)
  for (int i = 2784; i <= 2799; i++) i, // rows 87–87 (16 tiles)
  for (int i = 2816; i <= 2831; i++) i, // rows 88–88 (16 tiles)
  for (int i = 2848; i <= 2863; i++) i, // rows 89–89 (16 tiles)
  for (int i = 2880; i <= 2895; i++) i, // rows 90–90 (16 tiles)
  for (int i = 2912; i <= 2927; i++) i, // rows 91–91 (16 tiles)
  for (int i = 2944; i <= 2954; i++) i, // rows 92–92 (11 tiles)
  for (int i = 2976; i <= 2986; i++) i, // rows 93–93 (11 tiles)
};

/// All available tilesets.
final allTilesets = [
  testTileset,
  roomBuilderOffice,
  modernOffice,
  extTerrains,
  extWorksite,
  extHotelHospital,
  extSchool,
  extOffice,
];

// ---------------------------------------------------------------------------
// Barrier tile lookup
// ---------------------------------------------------------------------------

/// O(1) tileset lookup by ID, built once from [allTilesets].
final Map<String, Tileset> _tilesetLookup = {
  for (final ts in allTilesets) ts.id: ts,
};

/// Whether [ref] points to a tile tagged as a barrier in its tileset.
///
/// Returns `false` for unknown tilesets or tiles without barrier metadata.
bool isTileRefBarrier(TileRef ref) {
  final tileset = _tilesetLookup[ref.tilesetId];
  return tileset != null && tileset.isTileBarrier(ref.tileIndex);
}
