/// 8-bit Wang Blob bitmask utilities for auto-terrain tile selection.
///
/// Each cell's 8 Moore neighbors are encoded as a single byte:
///
/// ```
/// NW=128 | N=1  | NE=2
/// W=64   | cell | E=4
/// SW=32  | S=16 | SE=8
/// ```
///
/// Corner bits are only meaningful when both adjacent edge neighbors are
/// present (e.g. NE is irrelevant unless both N and E are set). Masking
/// out irrelevant corners reduces 256 raw values to **47 unique tile
/// configurations**.
library;

/// Direction bit constants and neighbor offsets for the 8-bit bitmask.
abstract final class Bitmask {
  // Cardinal / edge directions.
  static const int n = 1;
  static const int e = 4;
  static const int s = 16;
  static const int w = 64;

  // Diagonal / corner directions.
  static const int ne = 2;
  static const int se = 8;
  static const int sw = 32;
  static const int nw = 128;

  /// Neighbor offsets indexed by bit position (LSB → MSB).
  ///
  /// Index 0 = N (bit 0), 1 = NE (bit 1), 2 = E (bit 2), …, 7 = NW (bit 7).
  static const List<(int, int)> offsets = [
    (0, -1), // N
    (1, -1), // NE
    (1, 0), // E
    (1, 1), // SE
    (0, 1), // S
    (-1, 1), // SW
    (-1, 0), // W
    (-1, -1), // NW
  ];
}

/// Compute the raw 8-bit bitmask for the cell at ([cx], [cy]).
///
/// [isMatch] returns `true` when the neighbor at (x, y) belongs to the same
/// terrain type.
int computeRawBitmask(int cx, int cy, bool Function(int x, int y) isMatch) {
  var mask = 0;
  for (var i = 0; i < 8; i++) {
    final (dx, dy) = Bitmask.offsets[i];
    if (isMatch(cx + dx, cy + dy)) {
      mask |= 1 << i;
    }
  }
  return mask;
}

/// Simplify a raw bitmask by masking out corner bits whose adjacent edges
/// are not both present.
///
/// A corner is relevant only when both of its neighboring edge bits are set:
/// - NE requires N *and* E
/// - SE requires S *and* E
/// - SW requires S *and* W
/// - NW requires N *and* W
int simplifyBitmask(int raw) {
  var result = raw;
  if ((raw & Bitmask.n == 0) || (raw & Bitmask.e == 0)) {
    result &= ~Bitmask.ne;
  }
  if ((raw & Bitmask.s == 0) || (raw & Bitmask.e == 0)) {
    result &= ~Bitmask.se;
  }
  if ((raw & Bitmask.s == 0) || (raw & Bitmask.w == 0)) {
    result &= ~Bitmask.sw;
  }
  if ((raw & Bitmask.n == 0) || (raw & Bitmask.w == 0)) {
    result &= ~Bitmask.nw;
  }
  return result;
}

/// Compute the simplified bitmask for the cell at ([cx], [cy]).
///
/// Convenience function combining [computeRawBitmask] and [simplifyBitmask].
int computeBitmask(int cx, int cy, bool Function(int x, int y) isMatch) {
  return simplifyBitmask(computeRawBitmask(cx, cy, isMatch));
}

/// The complete set of 47 unique simplified bitmask values.
///
/// Generated by passing all 256 raw bitmasks through [simplifyBitmask] and
/// collecting the unique results.
final List<int> allSimplifiedBitmasks = () {
  final unique = <int>{};
  for (var raw = 0; raw < 256; raw++) {
    unique.add(simplifyBitmask(raw));
  }
  final sorted = unique.toList()..sort();
  return sorted;
}();
