// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhV44RI4PWf2ryoXq1h2EdqffQi3Ic_X0',
    appId: '1:614230417388:web:fcb71d2a30fd7615246ac9',
    messagingSenderId: '614230417388',
    projectId: 'adventures-in-tech-world-0',
    authDomain: 'adventures-in-tech-world-0.firebaseapp.com',
    storageBucket: 'adventures-in-tech-world-0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABbMDsGLMuKZPXD04uMmtyG3eJg0cFBFw',
    appId: '1:614230417388:ios:2dbbc66a8cb5e783246ac9',
    messagingSenderId: '614230417388',
    projectId: 'adventures-in-tech-world-0',
    storageBucket: 'adventures-in-tech-world-0.firebasestorage.app',
    iosBundleId: 'com.example.techWorld',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABbMDsGLMuKZPXD04uMmtyG3eJg0cFBFw',
    appId: '1:614230417388:ios:7a8907f854976dae246ac9',
    messagingSenderId: '614230417388',
    projectId: 'adventures-in-tech-world-0',
    storageBucket: 'adventures-in-tech-world-0.firebasestorage.app',
    iosBundleId: 'co.enspyr.techWorld',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA7dVjYsgdDf8pQdnd0lRXdFEdq4-Ca2k',
    appId: '1:614230417388:android:5bae8495326ad93d246ac9',
    messagingSenderId: '614230417388',
    projectId: 'adventures-in-tech-world-0',
    storageBucket: 'adventures-in-tech-world-0.firebasestorage.app',
  );

}