#!/usr/bin/env node
// A CORS-adding reverse proxy for realm-token-server, for the WEB DEV LOOP ONLY.
//
// WHY THIS EXISTS
//   realm-token-server sends no Access-Control-* headers on /exchange or
//   /livekit-token, AND rejects any request carrying an Origin header with
//   403 {"error":"origin not allowed"}. Measured 2026-09-11 against the live
//   host: 10 Origins tried (localhost variants, both Firebase Hosting domains,
//   tech-world.enspyr.co, dreamfinder.imagineering.cc) -- all 403. The SAME
//   request with no Origin header returns 401 "invalid id token", i.e. it is
//   reaching the auth logic. No positive control was found, so the allowlist's
//   actual contents are unknowable from outside; only the server's config can
//   say. A browser therefore cannot complete the exchange, and RealmTokenSource
//   reports it with the cause discarded (issue #3309).
//   Net effect: no browser can join a LiveKit room, which also makes
//   verify_av.sh's Concern 3 (Dreamfinder avatar bridge, Chrome-ONLY because
//   native exports a no-op stub) impossible to satisfy on any platform.
//
// WHAT THIS IS NOT
//   This is NOT a proposed fix for the server. Whether the server SHOULD send
//   CORS headers, and to which origins, is a question for the realm-token-server
//   source -- which is not in this repo. A previous CORS recommendation made
//   without reading that source would have caused a production outage. This
//   proxy changes nothing in production and is not evidence about what the
//   server's policy ought to be.
//
//   BE AWARE: this works by STRIPPING the Origin header, so it DEFEATS the
//   server's origin allowlist rather than supplying something missing. A
//   disclosed dev bypass, not a fix. The proper fix is server-side: add the
//   dev origin to the allowlist.
//
// TLS IS REQUIRED, NOT OPTIONAL
//   FirebaseAuthProvider throws ArgumentError unless exchangeEndpoint is https
//   (firebase_auth_provider.dart:47) -- the Firebase ID token would otherwise
//   travel in cleartext. ArgumentError is an Error, not an Exception, so it
//   escapes RealmTokenSource's handlers and surfaces as the deliberately
//   unhelpful "Token source threw unexpectedly".
//   This proxy therefore serves HTTPS with a self-signed cert, SATISFYING that
//   invariant rather than disabling it: the token is encrypted to the proxy and
//   re-encrypted upstream. The alternative -- wiring the provider's
//   allowInsecureExchangeEndpoint escape hatch -- would mean editing an auth
//   trust boundary for dev convenience, which is a worse trade.
//
// USAGE
//   node tool/cors_dev_proxy.js [port]            # default 8787, HTTPS
//   flutter run -d chrome --dart-define=REALM_TOKEN_BASE=https://localhost:8787
//
//   Or let the launcher do both:  CORS_PROXY=1 tool/dev_two_clients.sh
//
// SCOPE
//   Forwards every method and path straight through to UPSTREAM, preserving the
//   request body, Authorization (the BearerCredential hop-2 strategy) and
//   Content-Type. It reflects the caller's Origin rather than sending '*',
//   because '*' is incompatible with credentialed requests and would quietly
//   behave differently from a real fix.

const http = require('node:http');
const https = require('node:https');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');

const UPSTREAM = process.env.REALM_UPSTREAM ?? 'https://realm-token.imagineering.cc';
const PORT = Number(process.argv[2] ?? process.env.CORS_PROXY_PORT ?? 8787);

// Headers that must not be copied verbatim to the upstream fetch: hop-by-hop,
// or set by the fetch implementation itself.
const STRIP_REQUEST = new Set([
  'host', 'connection', 'keep-alive', 'transfer-encoding', 'upgrade',
  'proxy-authorization', 'proxy-connection', 'te', 'trailer',
  'content-length', 'accept-encoding', 'origin', 'referer',
]);

// Response headers that describe the upstream transport, not the payload.
const STRIP_RESPONSE = new Set([
  'content-encoding', 'content-length', 'transfer-encoding', 'connection',
  'keep-alive', 'alt-svc',
]);

function corsHeaders(req) {
  const origin = req.headers.origin;
  const headers = {
    'access-control-allow-methods': 'GET,POST,PUT,PATCH,DELETE,OPTIONS',
    'access-control-allow-headers':
      req.headers['access-control-request-headers'] ?? 'content-type,authorization',
    'access-control-max-age': '600',
    'vary': 'Origin',
  };
  if (origin) {
    headers['access-control-allow-origin'] = origin;
    headers['access-control-allow-credentials'] = 'true';
  } else {
    headers['access-control-allow-origin'] = '*';
  }
  return headers;
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', (c) => chunks.push(c));
    req.on('end', () => resolve(Buffer.concat(chunks)));
    req.on('error', reject);
  });
}

// Self-signed material, regenerated by tool/dev_two_clients.sh. Lives in the
// run dir (ephemeral, regenerable) rather than the repo -- a checked-in private
// key is a liability even when it only ever signs for localhost.
const CERT_DIR = process.env.PROXY_CERT_DIR
  ?? path.join(os.tmpdir(), 'tech-world-two-clients');
const CERT = path.join(CERT_DIR, 'proxy-cert.pem');
const KEY = path.join(CERT_DIR, 'proxy-key.pem');

const handler = async (req, res) => {
  const stamp = new Date().toISOString().slice(11, 23);

  if (req.method === 'OPTIONS') {
    res.writeHead(204, corsHeaders(req));
    res.end();
    console.log(`${stamp}  204 OPTIONS ${req.url}  (preflight answered locally)`);
    return;
  }

  const target = new URL(req.url, UPSTREAM);
  const headers = {};
  for (const [k, v] of Object.entries(req.headers)) {
    if (!STRIP_REQUEST.has(k.toLowerCase())) headers[k] = v;
  }

  try {
    const body = ['GET', 'HEAD'].includes(req.method) ? undefined : await readBody(req);
    const upstream = await fetch(target, {
      method: req.method,
      headers,
      body: body && body.length ? body : undefined,
      redirect: 'manual',
    });

    const out = { ...corsHeaders(req) };
    upstream.headers.forEach((value, key) => {
      if (!STRIP_RESPONSE.has(key.toLowerCase()) &&
          !key.toLowerCase().startsWith('access-control-')) {
        out[key] = value;
      }
    });

    const buf = Buffer.from(await upstream.arrayBuffer());
    res.writeHead(upstream.status, out);
    res.end(buf);
    console.log(`${stamp}  ${upstream.status} ${req.method} ${req.url}  -> ${target.host}`);
  } catch (err) {
    // Surface the cause rather than collapsing it to a generic failure — the
    // discarded-cause problem (#3309) is exactly what made this hard to find.
    res.writeHead(502, { ...corsHeaders(req), 'content-type': 'application/json' });
    res.end(JSON.stringify({ error: 'proxy_upstream_failure', detail: String(err) }));
    console.error(`${stamp}  502 ${req.method} ${req.url}  ${err}`);
  }
};

if (!fs.existsSync(CERT) || !fs.existsSync(KEY)) {
  console.error(`No cert at ${CERT}. Generate one with:`);
  console.error(`  openssl req -x509 -newkey rsa:2048 -nodes \\`);
  console.error(`    -keyout ${KEY} -out ${CERT} -days 30 \\`);
  console.error(`    -subj "/CN=localhost" -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"`);
  process.exit(1);
}

const server = https.createServer(
  { cert: fs.readFileSync(CERT), key: fs.readFileSync(KEY) },
  handler,
);

server.listen(PORT, '127.0.0.1', () => {
  console.log(`CORS dev proxy (HTTPS): https://localhost:${PORT}  ->  ${UPSTREAM}`);
  console.log(`Build the web client with:`);
  console.log(`  --dart-define=REALM_TOKEN_BASE=https://localhost:${PORT}`);
  console.log(`Chrome must trust the self-signed cert. Scope it to THIS cert`);
  console.log(`rather than disabling certificate checking wholesale:`);
  console.log(`  --web-browser-flag="--ignore-certificate-errors-spki-list=<sha256-b64>"`);
});
