#!/usr/bin/env node
// TLS in front of a LOCALLY-RUN realm-token-server, for the web dev loop.
//
// WHY A TERMINATOR AND NOT A CORS PROXY
//   Pointing at the PRODUCTION mint and stripping the Origin header defeats the
//   server's allowlist rather than supplying something missing. That rests on
//   the premise that the origin refusal is a gap to route around. It is not:
//   enspyrco/realm-token-server src/cors.js makes it a deliberate, documented
//   refusal -- `CORS_ALLOW_LOCALHOST=true` is REJECTED at
//   boot when NODE_ENV=production, and the Dockerfile sets NODE_ENV=production.
//   The deployed mint cannot be made to serve a laptop, on purpose -- the
//   opt-in "admits any port on loopback -- fine on a laptop, a hole on a public
//   mint".
//
//   The same repo already ships the answer: `scripts/dev.sh` runs the real
//   server locally with ephemeral keys, the real Firebase project id, and
//   CORS_ALLOW_LOCALHOST defaulted to true. Measured 2026-09-15: an OPTIONS
//   preflight from `http://localhost:62651` returns 204 with
//   `Access-Control-Allow-Origin: http://localhost:62651`. Nothing needs
//   bypassing, so this process adds NO headers and strips NONE.
//
// WHAT IS LEFT FOR IT TO DO
//   Exactly one thing: speak https. FirebaseAuthProvider throws ArgumentError
//   unless exchangeEndpoint is https (firebase_auth_provider.dart:47), because
//   the Firebase ID token would otherwise travel in cleartext. ArgumentError is
//   an Error, not an Exception, so it escapes RealmTokenSource's handlers and
//   surfaces as the deliberately unhelpful "Token source threw unexpectedly".
//   Terminating TLS here SATISFIES that invariant. The alternative -- wiring the
//   provider's allowInsecureExchangeEndpoint escape hatch through to production
//   code -- edits an auth trust boundary for dev convenience (claude-tasks#4253).
//
//   Because it adds nothing, the local server's real CORS policy is what the
//   browser sees: a disallowed origin still gets its 403. A dev loop that
//   cannot reproduce the production refusal is a dev loop that hides it.
//
// USAGE
//   Normally launched by tool/dev_two_clients.sh, which also starts the
//   upstream. By hand:
//     (cd ../../../enspyrco/realm-token-server && PORT=8790 ./scripts/dev.sh)
//     node tool/dev_tls_terminator.js 8787
//     flutter run -d chrome --dart-define=REALM_TOKEN_BASE=https://localhost:8787

const https = require('node:https');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');

const UPSTREAM = process.env.REALM_UPSTREAM ?? 'http://127.0.0.1:8790';
const PORT = Number(process.argv[2] ?? process.env.TLS_TERMINATOR_PORT ?? 8787);

// Hop-by-hop headers, or ones the fetch implementation sets itself. Origin is
// NOT in this list, and must never be: forwarding it verbatim is the whole
// difference between this and the proxy it replaces.
const STRIP_REQUEST = new Set([
  'host', 'connection', 'keep-alive', 'transfer-encoding', 'upgrade',
  'proxy-authorization', 'proxy-connection', 'te', 'trailer',
  'content-length', 'accept-encoding',
]);

const STRIP_RESPONSE = new Set([
  'content-encoding', 'content-length', 'transfer-encoding', 'connection',
  'keep-alive', 'alt-svc',
]);

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', (c) => chunks.push(c));
    req.on('end', () => resolve(Buffer.concat(chunks)));
    req.on('error', reject);
  });
}

// Self-signed material, regenerated by tool/dev_two_clients.sh. Lives in the
// run dir (ephemeral, regenerable) rather than the repo -- a checked-in private
// key is a liability even when it only ever signs for localhost.
const CERT_DIR = process.env.PROXY_CERT_DIR
  ?? path.join(os.tmpdir(), 'tech-world-two-clients');
const CERT = path.join(CERT_DIR, 'proxy-cert.pem');
const KEY = path.join(CERT_DIR, 'proxy-key.pem');

const handler = async (req, res) => {
  const stamp = new Date().toISOString().slice(11, 23);
  const target = new URL(req.url, UPSTREAM);

  const headers = {};
  for (const [k, v] of Object.entries(req.headers)) {
    if (!STRIP_REQUEST.has(k.toLowerCase())) headers[k] = v;
  }

  try {
    const body = ['GET', 'HEAD'].includes(req.method) ? undefined : await readBody(req);
    const upstream = await fetch(target, {
      method: req.method,
      headers,
      body: body && body.length ? body : undefined,
      redirect: 'manual',
    });

    // Every upstream header passes through, access-control-* included. The
    // preflight is answered by the real server, so what the browser enforces is
    // the real policy.
    const out = {};
    upstream.headers.forEach((value, key) => {
      if (!STRIP_RESPONSE.has(key.toLowerCase())) out[key] = value;
    });

    const buf = Buffer.from(await upstream.arrayBuffer());
    res.writeHead(upstream.status, out);
    res.end(buf);
    console.log(`${stamp}  ${upstream.status} ${req.method} ${req.url}`);
  } catch (err) {
    // Surface the cause rather than collapsing it to a generic failure -- the
    // discarded-cause problem (claude-tasks#3309) is what made this class of
    // failure hard to find in the first place. A connection refused here almost
    // always means the upstream dev server is not running.
    res.writeHead(502, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ error: 'upstream_unreachable', upstream: UPSTREAM, detail: String(err) }));
    console.error(`${stamp}  502 ${req.method} ${req.url}  ${err}`);
  }
};

if (!fs.existsSync(CERT) || !fs.existsSync(KEY)) {
  console.error(`No cert at ${CERT}. Generate one with:`);
  console.error(`  openssl req -x509 -newkey rsa:2048 -nodes \\`);
  console.error(`    -keyout ${KEY} -out ${CERT} -days 30 \\`);
  console.error(`    -subj "/CN=localhost" -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"`);
  process.exit(1);
}

const server = https.createServer(
  { cert: fs.readFileSync(CERT), key: fs.readFileSync(KEY) },
  handler,
);

server.listen(PORT, '127.0.0.1', () => {
  console.log(`TLS terminator: https://localhost:${PORT}  ->  ${UPSTREAM}`);
  console.log(`Adds no headers, strips none. Upstream must be a LOCAL`);
  console.log(`realm-token-server (scripts/dev.sh), not the production mint.`);
});
