import 'dart:math';

import 'package:logging/logging.dart';

import 'game_map.dart';
import 'l_room_tile_data.dart';
import 'l_room_wall_data.dart';
import 'map_parser.dart';

final _log = Logger('PredefinedMaps');

/// Open Arena - no barriers, free movement everywhere.
const openArena = GameMap(
  id: 'open_arena',
  name: 'Open Arena',
  barriers: [],
  spawnPoint: Point(25, 25),
);

/// Pre-computed L-Room wall grid (marks structural walls for cap generation).
final _lRoomWallGrid = _buildLRoomWallGrid();

WallGrid _buildLRoomWallGrid() {
  final grid = WallGrid();
  for (final b in lRoomWallBarriers) {
    grid.setWall(b.x, b.y, 'gray_brick');
  }
  return grid;
}

/// The L-Room - original map with tile-based offline fallback.
///
/// No pre-built objectLayer — `buildObjectLayerFromBarriers` generates it at
/// runtime (copies floor tiles at ALL barrier positions for depth sorting).
/// The [wallGrid] tells the renderer to add cap tiles at y-1 above structural
/// walls for wall-top occlusion.
final lRoom = GameMap(
  id: 'l_room',
  name: 'The L-Room',
  barriers: lRoomWallBarriers,
  spawnPoint: const Point(10, 15),
  terminals: const [Point(8, 12), Point(14, 12)],
  floorLayer: buildLRoomFloorLayer(),
  tilesetIds: const ['single_room'],
  wallGrid: _lRoomWallGrid,
);

/// Four Corners - open map, barriers come from painted tiles.
const fourCorners = GameMap(
  id: 'four_corners',
  name: 'Four Corners',
  barriers: [],
  spawnPoint: Point(25, 25),
);

/// Simple Maze - barriers come from painted tiles.
const simpleMaze = GameMap(
  id: 'simple_maze',
  name: 'Simple Maze',
  barriers: [],
  spawnPoint: Point(8, 8),
);

// ---------------------------------------------------------------------------
// ASCII art maps - spawn and terminal placement only (no barriers).
//
// Legend: . = open, S = spawn, T = terminal
// Each map is a 50x50 grid (gridSize from constants.dart).
// ---------------------------------------------------------------------------

/// The Library - a quiet study space with terminal stations at study desks.
/// Barriers come from painted tiles; ASCII defines only spawn and terminals.
final theLibrary = parseAsciiMap(
  id: 'the_library',
  name: 'The Library',
  ascii: _theLibraryAscii,
);

/// The Workshop - a maker space with open collaboration areas and terminals.
/// Barriers come from painted tiles; ASCII defines only spawn and terminals.
final theWorkshop = parseAsciiMap(
  id: 'the_workshop',
  name: 'The Workshop',
  ascii: _theWorkshopAscii,
);

/// All available maps.
final allMaps = [
  openArena,
  lRoom,
  fourCorners,
  simpleMaze,
  theLibrary,
  theWorkshop,
];

/// Default map to use when none is specified.
final defaultMap = lRoom;

/// O(1) lookup of predefined maps by ID.
final Map<String, GameMap> _predefinedMapLookup = {
  for (final m in allMaps) m.id: m,
};

/// Fill in missing visual layers from a predefined map, if one exists.
///
/// When a [GameMap] is loaded from Firestore, it may predate the addition
/// of tileset-based rendering. This finds the matching predefined map and
/// merges in its visual layers (floor, object, tilesetIds) without overriding
/// any structural data (barriers, spawn, terminals) or any visual data the
/// Firestore version already has.
///
/// Matching works two ways:
/// 1. By map ID (for predefined maps used directly).
/// 2. By structural fingerprint — Firestore rooms get the document ID as
///    their map ID, so the original predefined ID is lost. We match by
///    comparing the barrier set, which is a unique structural signature.
///
/// Returns [map] unchanged if there is no predefined match or nothing to fill.
GameMap applyPredefinedVisualFallback(GameMap map) {
  // Already has ALL visual layers — nothing to fill.
  if (map.floorLayer != null && map.objectLayer != null) {
    _log.fine('Visual fallback skipped: "${map.name}" already has all visual layers');
    return map;
  }

  _log.info('Visual fallback: "${map.name}" (id=${map.id}), '
      'floorLayer=${map.floorLayer != null}, objectLayer=${map.objectLayer != null}');

  final predefined = _findPredefinedMatch(map);
  if (predefined == null) return map;

  // Merge each missing layer independently. A Firestore map might have a
  // floor layer from before wall tiles existed but no object layer — we
  // still want to fill in the wall object layer from the predefined match.
  final needsFloor = map.floorLayer == null && predefined.floorLayer != null;
  final needsObjects =
      map.objectLayer == null && predefined.objectLayer != null;
  final needsTilesetIds =
      predefined.tilesetIds.isNotEmpty &&
      !predefined.tilesetIds.every(map.tilesetIds.contains);
  final needsWallGrid =
      map.wallGrid == null && predefined.wallGrid != null;

  if (!needsFloor && !needsObjects && !needsTilesetIds && !needsWallGrid) {
    return map;
  }

  // Merge tileset IDs from both sources (deduped, order-preserving).
  final mergedTilesetIds = {...map.tilesetIds, ...predefined.tilesetIds}.toList();

  return GameMap(
    id: map.id,
    name: map.name,
    barriers: map.barriers,
    spawnPoint: map.spawnPoint,
    terminals: map.terminals,
    floorLayer: map.floorLayer ?? predefined.floorLayer,
    objectLayer: map.objectLayer ?? predefined.objectLayer,
    objectLayerPriorityOverrides: predefined.objectLayerPriorityOverrides,
    tilesetIds: mergedTilesetIds,
    terrainGrid: map.terrainGrid ?? predefined.terrainGrid,
    customTilesets: map.customTilesets,
    wallGrid: map.wallGrid ?? predefined.wallGrid,
  );
}

/// Find a predefined map matching [map], by ID, name, or barrier structure.
GameMap? _findPredefinedMatch(GameMap map) {
  // Fast path: direct ID match (for predefined maps used without Firestore).
  final byId = _predefinedMapLookup[map.id];
  if (byId != null) {
    _log.info('Visual fallback: matched by ID "${map.id}"');
    return byId;
  }

  // Only consider predefined maps with visual layers worth merging.
  final candidates =
      allMaps.where((m) => m.floorLayer != null || m.objectLayer != null);

  // Match by name — Firestore rooms preserve the map name at the room level.
  for (final predefined in candidates) {
    if (predefined.name == map.name) {
      _log.info('Visual fallback: matched by name "${map.name}"');
      return predefined;
    }
  }

  // Match by barrier fingerprint — structural comparison.
  if (map.barriers.isNotEmpty) {
    final mapBarrierSet = Set<Point<int>>.from(map.barriers);
    for (final predefined in candidates) {
      if (predefined.barriers.length != mapBarrierSet.length) continue;
      if (Set<Point<int>>.from(predefined.barriers)
          .containsAll(mapBarrierSet)) {
        _log.info(
            'Visual fallback: matched by barriers → "${predefined.name}"');
        return predefined;
      }
    }
  }

  _log.fine('Visual fallback: no match for "${map.id}" / "${map.name}"');
  return null;
}

// ---------------------------------------------------------------------------
// ASCII art map data — barriers removed, only spawn (S) and terminals (T).
// ---------------------------------------------------------------------------

//       0         1         2         3         4
//       0123456789012345678901234567890123456789012345678901
const _theLibraryAscii = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
.....T......T......T......T.......................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
.............S....................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................''';

//       0         1         2         3         4
//       0123456789012345678901234567890123456789012345678901
const _theWorkshopAscii = '''
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..............T...................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..............T...................................
..................................................
..................................................
..................................................
..................................................
.........S........................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................''';
